//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKLabelNode, SKSpriteNode, Sprite;

@interface ActionButton : SKNode
{
    float sc;
    Sprite *bg;
    SKLabelNode *txt;
    SKLabelNode *txt2;
    SEL action;
    SKSpriteNode *shadow;
    SKNode *container;
    struct CGSize offset;
    struct CGSize margins;
}

@property struct CGSize margins; // @synthesize margins;
@property(retain) SKNode *container; // @synthesize container;
@property struct CGSize offset; // @synthesize offset;
@property float sc; // @synthesize sc;
@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
@property SEL action; // @synthesize action;
@property(retain) SKLabelNode *txt2; // @synthesize txt2;
@property(retain) SKLabelNode *txt; // @synthesize txt;
@property(retain) Sprite *bg; // @synthesize bg;
- (void).cxx_destruct;
- (void)up;
- (void)down;
- (void)setAnagrams;
- (void)setOutlineButtonActive;
- (void)setOutlineButtonInactive;
- (void)setBlackButtonActive;
- (void)setBlackButtonInactive;
- (void)setBlue2;
- (void)setBlue;
- (void)setRed;
- (void)setGreen;
- (void)setYellowButton;
- (void)scaleText;
- (void)setButtonText:(id)arg1;
- (void)setText:(id)arg1;
- (void)setText:(id)arg1 text2:(id)arg2;
- (void)setSize:(float)arg1;
- (id)init;

@end

