//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKSpriteNode.h"

@class SKLabelNode, Sprite;

@interface ActionNode : SKSpriteNode
{
    Sprite *bg;
    SKLabelNode *txt;
    SEL action;
}

@property SEL action; // @synthesize action;
@property(retain) SKLabelNode *txt; // @synthesize txt;
@property(retain) Sprite *bg; // @synthesize bg;
- (void).cxx_destruct;
- (void)up;
- (void)down;
- (void)setYellowButton;
- (void)setBlueButton;
- (id)init;

@end

