//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class NSDictionary, NSString, SKLabelNode, SKSpriteNode;

@interface AnagramsWordList : SKNode
{
    SKLabelNode *score_node;
    SKLabelNode *word_node;
    SKLabelNode *more;
    SKNode *score_container;
    SKLabelNode *q;
    _Bool right;
    _Bool gray;
    _Bool _active;
    int words;
    int _score;
    NSString *words_string;
    SKSpriteNode *bg;
    SKSpriteNode *score_bg;
    SKNode *word_list;
    NSDictionary *_dict_c;
    NSString *_game;
    SKNode *_selected;
    SKLabelNode *_score_node;
}

@property(retain) SKLabelNode *score_node; // @synthesize score_node=_score_node;
@property int score; // @synthesize score=_score;
@property _Bool active; // @synthesize active=_active;
@property(retain) SKNode *selected; // @synthesize selected=_selected;
@property(retain) NSString *game; // @synthesize game=_game;
@property(retain) NSDictionary *dict_c; // @synthesize dict_c=_dict_c;
@property(retain) SKNode *word_list; // @synthesize word_list;
@property(retain) SKSpriteNode *score_bg; // @synthesize score_bg;
@property _Bool gray; // @synthesize gray;
@property(retain) SKSpriteNode *bg; // @synthesize bg;
@property int words; // @synthesize words;
@property(retain) NSString *words_string; // @synthesize words_string;
- (void).cxx_destruct;
- (void)reveal;
- (void)setWordList:(id)arg1;
- (void)Gray;
- (void)setEnemy;
- (id)init;

@end

