//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameScene.h"

@class ActionButton, AnagramsBackButton, AnagramsGoal, AnagramsRevealButton, AnagramsScore, AnagramsStore, AnagramsWordList, AvatarNode, NSDate, NSDictionary, NSMutableArray, NSString, SKAudioNode, SKCropNode, SKLabelNode, SKMultilineLabel, SKNode, SKSpriteNode, ShuffleButton, TipNode;

@interface AnagramsScene : GameScene
{
    _Bool scrolled;
    struct CGPoint last_touch;
    AnagramsWordList *wordList;
    AnagramsRevealButton *revealButton;
    SKCropNode *wordListCrop;
    SKSpriteNode *wordListMask;
    AnagramsStore *store;
    AnagramsBackButton *backButton;
    AnagramsBackButton *backButton2;
    AnagramsBackButton *storeButton;
    SKSpriteNode *preloader_bg;
    SKSpriteNode *preloader_indicator;
    SKNode *preloader;
    SKSpriteNode *preloader2_bg;
    SKSpriteNode *preloader2_indicator;
    SKNode *preloader2;
    SKAudioNode *counting;
    SKAudioNode *ticker;
    shared_ptr_352a3a4b counting2;
    shared_ptr_352a3a4b ticker2;
    SKNode *board;
    ActionButton *enter;
    NSMutableArray *blocks;
    NSMutableArray *answer;
    SKNode *selected;
    int words;
    int score;
    float score_it;
    SKNode *stage;
    ActionButton *view_all;
    AnagramsGoal *tutorial;
    AvatarNode *score_avatar;
    SKLabelNode *score_words;
    SKLabelNode *score_score;
    SKSpriteNode *score_bg;
    SKNode *score_container;
    SKSpriteNode *time_bg;
    SKLabelNode *time_label;
    SKNode *time_node;
    SKNode *bg_pattern;
    SKSpriteNode *paper;
    SKLabelNode *score_node;
    SKLabelNode *word_node;
    SKSpriteNode *timer_node;
    SKSpriteNode *timer_arrow;
    SKLabelNode *timer_label;
    SKSpriteNode *timer_arrow2;
    int time;
    TipNode *tip;
    NSDate *start_time;
    NSMutableArray *words_ar;
    NSDictionary *dict;
    NSDictionary *dict_c;
    int state;
    SKNode *how;
    SKMultilineLabel *how_label;
    SKMultilineLabel *how_timer;
    ActionButton *start;
    SKSpriteNode *start_timer;
    ActionButton *send;
    AnagramsScore *result;
    AnagramsScore *result2;
    _Bool sent;
    int player;
    _Bool mine;
    NSString *letters;
    NSString *player_id1;
    NSString *player_id2;
    ShuffleButton *shuffle;
    SKNode *glows;
    NSMutableArray *marks;
    NSString *lang;
    int size;
    _Bool created;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)resize;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (void)update:(double)arg1;
- (void)purchaseComplete;
- (struct CGPoint)Slerp:(struct CGPoint)arg1 pos2:(struct CGPoint)arg2 ratio:(float)arg3;
- (void)enterWord;
- (void)toResult;
- (void)sendComplete;
- (void)showViewAllButton;
- (void)showAllState;
- (void)backAction;
- (void)toStoreAction;
- (void)backAction2;
- (void)revealWords:(_Bool)arg1;
- (void)revealAction;
- (void)revealActionComplete;
- (void)winGame;
- (void)saveScore;
- (void)unload;
- (void)startGame;
- (void)sendMessage;
- (id)generateWord:(id)arg1 size:(int)arg2;
- (void)savePlaceBack:(id)arg1 what:(id)arg2;
- (void)placeBack:(id)arg1;
- (id)generatePreview;
- (void)Shuffle;
- (id)loadDict:(id)arg1;
- (void)receiveMessage:(id)arg1;
- (void)createSceneContents;
- (void)didMoveToView:(id)arg1;
- (id)initWithMain:(id)arg1 msg:(id)arg2;

@end

