//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKLabelNode, SKSpriteNode, Sprite;

@interface AnagramsRevealButton : SKNode
{
    _Bool _active;
    float sc;
    Sprite *bg;
    SKLabelNode *txt;
    SKLabelNode *txt2;
    SEL action;
    SKSpriteNode *shadow;
    SKNode *container;
    SKNode *counter;
    SKSpriteNode *counter_bg;
    SKLabelNode *counter_txt;
    struct CGSize offset;
    struct CGSize margins;
}

@property _Bool active; // @synthesize active=_active;
@property(retain) SKLabelNode *counter_txt; // @synthesize counter_txt;
@property(retain) SKSpriteNode *counter_bg; // @synthesize counter_bg;
@property(retain) SKNode *counter; // @synthesize counter;
@property struct CGSize margins; // @synthesize margins;
@property(retain) SKNode *container; // @synthesize container;
@property struct CGSize offset; // @synthesize offset;
@property float sc; // @synthesize sc;
@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
@property SEL action; // @synthesize action;
@property(retain) SKLabelNode *txt2; // @synthesize txt2;
@property(retain) SKLabelNode *txt; // @synthesize txt;
@property(retain) Sprite *bg; // @synthesize bg;
- (void).cxx_destruct;
- (void)update;
- (void)up;
- (void)down;
- (void)setCount:(int)arg1;
- (void)inactive;
- (id)init;

@end

