//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class ActionButton, SKLabelNode, SKMultilineLabel, SKSpriteNode, Sprite;

@interface AnagramsGoal : SKNode
{
    SKSpriteNode *shadow;
    SKNode *container;
    SKNode *how;
    Sprite *bg;
    ActionButton *start;
    SKMultilineLabel *q;
    SKLabelNode *goal;
}

@property(retain) SKLabelNode *goal; // @synthesize goal;
@property(retain) SKMultilineLabel *q; // @synthesize q;
@property(retain) ActionButton *start; // @synthesize start;
@property(retain) Sprite *bg; // @synthesize bg;
- (void).cxx_destruct;
- (void)hunt;
- (void)wordbites;
- (void)setMode:(int)arg1;
- (id)init;

@end

