//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameSettings.h"

@class NSMutableArray, NSString, SettingsCustomizeButton, SettingsOptionButton, SettingsOptionPartition;

@interface AnagramsSettings : GameSettings
{
    int state;
    NSMutableArray *locks;
    SettingsOptionPartition *part1;
    SettingsOptionPartition *part2;
    SettingsOptionPartition *part3;
    SettingsOptionButton *option1;
    SettingsOptionButton *option2;
    SettingsOptionButton *option3;
    SettingsOptionButton *lang1;
    SettingsOptionButton *lang2;
    SettingsOptionButton *lang3;
    SettingsOptionButton *lang4;
    SettingsOptionButton *lang5;
    SettingsOptionButton *lang6;
    SettingsCustomizeButton *customize;
    NSString *lang;
    NSString *size;
}

@property(retain) NSString *size; // @synthesize size;
@property(retain) NSString *lang; // @synthesize lang;
- (void).cxx_destruct;
- (void)selectLanguage:(id)arg1;
- (void)selectSize:(id)arg1;
- (void)sLang:(id)arg1;
- (void)sSize:(id)arg1;
- (void)update;
- (void)resize;
- (id)init;

@end

