//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class ActionButton, NSString, SKLabelNode;

@interface AnagramsStoreButton : SKNode
{
    SKLabelNode *txt;
    SKNode *container;
    ActionButton *button;
    NSString *_store_id;
    id _target;
    SEL _action;
}

@property SEL action; // @synthesize action=_action;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(retain) NSString *store_id; // @synthesize store_id=_store_id;
@property(retain) ActionButton *button; // @synthesize button;
@property(retain) SKNode *container; // @synthesize container;
@property(retain) SKLabelNode *txt; // @synthesize txt;
- (void).cxx_destruct;
- (void)up;
- (void)down;
- (void)setItem:(id)arg1 label:(id)arg2 price:(id)arg3;
- (id)init;

@end

