//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class AnagramsStoreButton, SKLabelNode, SKSpriteNode;

@interface AnagramsStore : SKNode
{
    SKLabelNode *you_have1;
    SKLabelNode *you_have2;
    SKLabelNode *you_have3;
    SKLabelNode *you_have_num;
    SKLabelNode *compatible1;
    SKLabelNode *compatible2;
    SKNode *you_have;
    AnagramsStoreButton *button1;
    AnagramsStoreButton *button2;
    AnagramsStoreButton *button3;
    AnagramsStoreButton *button4;
    SKNode *compatible;
    SKSpriteNode *_indicator;
}

@property(retain) SKSpriteNode *indicator; // @synthesize indicator=_indicator;
@property(retain) SKNode *compatible; // @synthesize compatible;
@property(retain) AnagramsStoreButton *button4; // @synthesize button4;
@property(retain) AnagramsStoreButton *button3; // @synthesize button3;
@property(retain) AnagramsStoreButton *button2; // @synthesize button2;
@property(retain) AnagramsStoreButton *button1; // @synthesize button1;
@property(retain) SKNode *you_have; // @synthesize you_have;
- (void).cxx_destruct;
- (void)updateReveals;
- (void)update;
- (void)resize:(struct CGSize)arg1;
- (void)buyReveals:(id)arg1;
- (void)buy4;
- (void)buy3;
- (void)buy2;
- (void)buy1;
- (id)init;
- (void)setNum:(int)arg1;

@end

