//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MPBaseAdapterConfiguration.h"

@class NSString;

@interface AppLovinAdapterConfiguration : MPBaseAdapterConfiguration
{
}

+ (void)setSdkKey:(id)arg1;
+ (id)sdkKey;
+ (id)pluginVersion;
- (id)SDKFromConfiguration:(id)arg1;
- (void)initializeNetworkWithConfiguration:(id)arg1 complete:(CDUnknownBlockType)arg2;
@property(readonly, copy, nonatomic) NSString *networkSdkVersion;
@property(readonly, copy, nonatomic) NSString *moPubNetworkName;
@property(readonly, copy, nonatomic) NSString *biddingToken;
@property(readonly, copy, nonatomic) NSString *adapterVersion;

@end

