//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MPNativeCustomEvent.h"

#import "ALAdDisplayDelegate.h"
#import "ALAdLoadDelegate.h"
#import "ALNativeAdLoadDelegate.h"
#import "ALNativeAdPrecacheDelegate.h"

@class ALCarouselCardView, ALCarouselMediaView, AppLovinNativeAdAdapter, NSString;

@interface AppLovinNativeCustomEvent : MPNativeCustomEvent <ALNativeAdLoadDelegate, ALNativeAdPrecacheDelegate, ALAdLoadDelegate, ALAdDisplayDelegate>
{
    _Bool _rendering_ad;
    AppLovinNativeAdAdapter *_adAdapter;
    ALCarouselMediaView *_med;
    ALCarouselCardView *_card;
}

@property _Bool rendering_ad; // @synthesize rendering_ad=_rendering_ad;
@property(retain, nonatomic) ALCarouselCardView *card; // @synthesize card=_card;
@property(retain, nonatomic) ALCarouselMediaView *med; // @synthesize med=_med;
@property(retain, nonatomic) AppLovinNativeAdAdapter *adAdapter; // @synthesize adAdapter=_adAdapter;
- (void).cxx_destruct;
- (void)nativeAdService:(id)arg1 didLoadAds:(id)arg2;
- (void)nativeAdService:(id)arg1 didFailToPrecacheImagesForAd:(id)arg2 withError:(long long)arg3;
- (void)nativeAdService:(id)arg1 didFailToPrecacheVideoForAd:(id)arg2 withError:(long long)arg3;
- (void)nativeAdService:(id)arg1 didFailToLoadAdsWithError:(long long)arg2;
- (void)nativeAdService:(id)arg1 didPrecacheVideoForAd:(id)arg2;
- (void)nativeAdService:(id)arg1 didPrecacheImagesForAd:(id)arg2;
- (void)renderAd:(id)arg1;
- (void)requestAdWithCustomEventInfo:(id)arg1 adMarkup:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

