//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MPRewardedVideoCustomEvent.h"

#import "ALAdDisplayDelegate.h"
#import "ALAdLoadDelegate.h"
#import "ALAdRewardDelegate.h"
#import "ALAdVideoPlaybackDelegate.h"

@class ALAd, ALIncentivizedInterstitialAd, ALSdk, MPRewardedVideoReward, NSString;

@interface AppLovinRewardedVideoCustomEvent : MPRewardedVideoCustomEvent <ALAdLoadDelegate, ALAdDisplayDelegate, ALAdVideoPlaybackDelegate, ALAdRewardDelegate>
{
    _Bool _fullyWatched;
    _Bool _tokenEvent;
    ALSdk *_sdk;
    ALIncentivizedInterstitialAd *_incent;
    MPRewardedVideoReward *_reward;
    ALAd *_tokenAd;
    NSString *_zoneIdentifier;
}

+ (id)incentivizedInterstitialAdForZoneIdentifier:(id)arg1 customEvent:(id)arg2 sdk:(id)arg3;
+ (void)initialize;
@property(copy, nonatomic) NSString *zoneIdentifier; // @synthesize zoneIdentifier=_zoneIdentifier;
@property(retain, nonatomic) ALAd *tokenAd; // @synthesize tokenAd=_tokenAd;
@property(nonatomic, getter=isTokenEvent) _Bool tokenEvent; // @synthesize tokenEvent=_tokenEvent;
@property(retain, nonatomic) MPRewardedVideoReward *reward; // @synthesize reward=_reward;
@property(nonatomic) _Bool fullyWatched; // @synthesize fullyWatched=_fullyWatched;
@property(retain, nonatomic) ALIncentivizedInterstitialAd *incent; // @synthesize incent=_incent;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (void).cxx_destruct;
- (id)getAdNetworkId;
- (id)SDKFromCustomEventInfo:(id)arg1;
- (int)toMoPubErrorCode:(int)arg1;
- (void)rewardValidationRequestForAd:(id)arg1 didSucceedWithResponse:(id)arg2;
- (void)rewardValidationRequestForAd:(id)arg1 wasRejectedWithResponse:(id)arg2;
- (void)rewardValidationRequestForAd:(id)arg1 didFailWithError:(long long)arg2;
- (void)rewardValidationRequestForAd:(id)arg1 didExceedQuotaWithResponse:(id)arg2;
- (void)videoPlaybackEndedInAd:(id)arg1 atPlaybackPercent:(id)arg2 fullyWatched:(_Bool)arg3;
- (void)videoPlaybackBeganInAd:(id)arg1;
- (void)ad:(id)arg1 wasClickedIn:(id)arg2;
- (void)ad:(id)arg1 wasHiddenIn:(id)arg2;
- (void)ad:(id)arg1 wasDisplayedIn:(id)arg2;
- (void)adService:(id)arg1 didFailToLoadAdWithError:(int)arg2;
- (void)adService:(id)arg1 didLoadAd:(id)arg2;
- (void)handleAdPlayedForCustomEventNetwork;
- (void)handleCustomEventInvalidated;
- (void)presentRewardedVideoFromViewController:(id)arg1;
- (_Bool)hasAdAvailable;
- (void)requestRewardedVideoWithCustomEventInfo:(id)arg1 adMarkup:(id)arg2;
- (void)requestRewardedVideoWithCustomEventInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

