//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameScene.h"

@class ArcheryView, NSDate, NSMutableArray, NSMutableString, NSString, SKLabelNode, SKNode, SKShapeNode, SKSpriteNode;

@interface ArcheryScene : GameScene
{
    NSMutableString *replay_send;
    NSMutableArray *replay;
    int state;
    int player;
    int player2;
    NSString *player_id1;
    NSString *player_id2;
    int seed;
    _Bool sent;
    SKNode *selected;
    SKSpriteNode *rect;
    SKSpriteNode *wind_rect;
    SKSpriteNode *wind_circle;
    SKSpriteNode *wind_arrow;
    SKLabelNode *wind_label;
    SKLabelNode *wind_value_label;
    SKSpriteNode *aim_mask2;
    SKSpriteNode *aim_mask;
    SKSpriteNode *top_ui_background;
    SKLabelNode *top_ui_set;
    SKLabelNode *top_ui_score;
    SKLabelNode *top_ui_set_score1;
    SKLabelNode *top_ui_set_score2;
    float score_display1;
    float score_display2;
    NSDate *counter_date;
    SKSpriteNode *medal1;
    SKSpriteNode *medal2;
    SKLabelNode *medal_label1;
    SKLabelNode *medal_label2;
    SKNode *notice;
    SKSpriteNode *notice_background;
    SKSpriteNode *notice_line;
    SKNode *notice_hand;
    SKSpriteNode *notice_hand2;
    SKSpriteNode *notice_circle;
    _Bool center_ui;
    int shots;
    SKShapeNode *_spinnyNode;
    SKLabelNode *_label;
    float wind_angle;
    float wind_power;
    int score1;
    int score2;
    int total_score1;
    int total_score2;
    int set_num;
    float _ratio;
    ArcheryView *scene3d;
    SKNode *wind_ui;
    SKNode *aim;
    SKNode *aim_countdown;
    SKNode *top_ui;
}

@property float ratio; // @synthesize ratio=_ratio;
@property int set_num; // @synthesize set_num;
@property int total_score2; // @synthesize total_score2;
@property int total_score1; // @synthesize total_score1;
@property int score2; // @synthesize score2;
@property int score1; // @synthesize score1;
@property(retain) SKNode *top_ui; // @synthesize top_ui;
@property(retain) SKNode *aim_countdown; // @synthesize aim_countdown;
@property(retain) SKNode *aim; // @synthesize aim;
@property float wind_power; // @synthesize wind_power;
@property float wind_angle; // @synthesize wind_angle;
@property(retain) SKNode *wind_ui; // @synthesize wind_ui;
@property(retain) ArcheryView *scene3d; // @synthesize scene3d;
- (void).cxx_destruct;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)unload;
- (void)resize;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (struct CGPoint)Slerp:(struct CGPoint)arg1 pos2:(struct CGPoint)arg2 ratio:(float)arg3;
- (struct CGSize)stageSize2;
- (void)update:(double)arg1;
- (void)sendMessage;
- (void)checkWin;
- (void)endShot:(int)arg1 x:(float)arg2 y:(float)arg3 z:(float)arg4 score:(int)arg5;
- (void)feedback:(int)arg1;
- (void)playCounter;
- (void)setWind:(float)arg1 angle:(float)arg2;
- (void)setWind;
- (void)showScore:(int)arg1;
- (void)showPlus:(id)arg1;
- (void)sco2;
- (void)sco;
- (void)addAim;
- (void)setCountdown:(float)arg1;
- (id)parseReplay:(id)arg1;
- (void)endReplay;
- (void)playReplay;
- (void)skip;
- (void)saveMove:(struct SCNVector3)arg1 type:(int)arg2;
- (void)receiveMessage:(id)arg1;
- (void)showNotice;
- (void)hideNotice;
- (void)createSceneContents;
- (void)didMoveToView:(id)arg1;
- (id)initWithMain:(id)arg1 msg:(id)arg2;

@end

