//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCNView.h"

#import "SCNPhysicsContactDelegate.h"
#import "SCNSceneRendererDelegate.h"

@class ArcheryArrow, NSDate, NSMutableArray, NSMutableString, NSString, NSTimer, SCNGeometry, SCNNode, SCNPhysicsBody, SCNScene, SKAudioNode, SKScene, UIImageView;

@interface ArcheryView : SCNView <SCNPhysicsContactDelegate, SCNSceneRendererDelegate>
{
    UIImageView *aim_view;
    struct CGPoint aim_origin;
    struct CGPoint aim_pos;
    struct CGPoint aim_speed;
    float aim_breath;
    int shot_time;
    NSMutableArray *arrows;
    SCNNode *gameball;
    _Bool alphaing;
    SCNNode *weapon;
    SCNNode *table;
    SCNNode *cam;
    SCNNode *paddle;
    _Bool first_press;
    struct CGPoint first_press_pos;
    SCNNode *paddle_shadow;
    SCNNode *gameball_shadow;
    NSMutableArray *highlight_textures;
    SCNNode *highlight;
    SCNNode *grass;
    SCNNode *target;
    SCNNode *target2;
    SCNNode *target_front;
    SCNNode *weapon_arrow;
    SCNNode *arrow_shadow;
    SCNNode *plack;
    ArcheryArrow *arrow;
    struct SCNVector3 arrow_target;
    SCNNode *rayplane;
    SCNNode *pole1;
    SCNNode *pole2;
    SCNNode *ball;
    SCNNode *basket;
    SCNNode *basket_main;
    SCNNode *net;
    SCNNode *net2;
    SCNNode *net_col;
    SCNNode *ball_shadow;
    SCNNode *selected;
    SCNPhysicsBody *selected_body;
    SCNScene *scene;
    float speed;
    float speed_x;
    struct CGPoint touch_start;
    struct CGPoint prev_pos;
    struct CGPoint touch_pos;
    struct CGPoint prev_pos2;
    struct CGVector vec;
    int last_shot;
    int last_shot2;
    int net_frame;
    NSMutableArray *balls;
    SCNNode *count11;
    SCNNode *count12;
    SCNNode *count21;
    SCNNode *count22;
    SCNNode *time1;
    SCNNode *time2;
    int times1;
    int times2;
    SCNGeometry *mat2;
    NSDate *last_bounce;
    NSDate *last_rim;
    NSTimer *timer2;
    NSMutableArray *net4_textures;
    NSMutableArray *net3_textures;
    NSMutableArray *num_textures;
    NSDate *last;
    int shot_back_timer;
    SKAudioNode *wind_sound;
    SKAudioNode *press_sound;
    _Bool stopped;
    _Bool touching;
    _Bool _save_shoot;
    int state;
    int seed;
    int score1;
    int score2;
    int player;
    int timer;
    int times;
    float ratio;
    int time;
    float _miny;
    int _save_type;
    NSMutableString *replay_send;
    NSDate *start_time;
    NSMutableArray *replay1;
    NSMutableArray *replay2;
    NSString *mode;
    SKScene *sk_scene;
    struct SCNVector3 _save_point;
}

@property _Bool save_shoot; // @synthesize save_shoot=_save_shoot;
@property int save_type; // @synthesize save_type=_save_type;
@property struct SCNVector3 save_point; // @synthesize save_point=_save_point;
@property float miny; // @synthesize miny=_miny;
@property _Bool touching; // @synthesize touching;
@property _Bool stopped; // @synthesize stopped;
@property(retain) SKScene *sk_scene; // @synthesize sk_scene;
@property int time; // @synthesize time;
@property(retain) NSString *mode; // @synthesize mode;
@property float ratio; // @synthesize ratio;
@property int times; // @synthesize times;
@property int timer; // @synthesize timer;
@property int player; // @synthesize player;
@property(retain) NSMutableArray *replay2; // @synthesize replay2;
@property(retain) NSMutableArray *replay1; // @synthesize replay1;
@property int score2; // @synthesize score2;
@property int score1; // @synthesize score1;
@property int seed; // @synthesize seed;
@property int state; // @synthesize state;
@property(retain) NSDate *start_time; // @synthesize start_time;
@property(retain) NSMutableString *replay_send; // @synthesize replay_send;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)prefersStatusBarHidden;
- (_Bool)shouldAutorotate;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)Skip;
- (void)renderer:(id)arg1 updateAtTime:(double)arg2;
- (void)spawn:(int)arg1;
- (void)spawn;
- (void)rem:(id)arg1;
- (void)unload;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)update;
- (void)removeArrows;
- (void)hitArrow:(id)arg1;
- (void)shoot;
- (void)shoot2:(int)arg1 x:(float)arg2 y:(float)arg3 z:(float)arg4;
- (void)update2;
- (void)start;
- (void)resetShot;
- (void)setTargetDistance:(int)arg1;
- (void)setTargetDistance;
- (void)createScene;
- (void)renderer:(id)arg1 didSimulatePhysicsAtTime:(double)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

