//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCNNode;

@interface ArcheryArrow : NSObject
{
    _Bool _miss;
    _Bool _stopped;
    int _target_type;
    float _wave;
    float _wave_height;
    SCNNode *_arrow;
    SCNNode *_shadow;
    struct SCNVector3 _target;
    struct SCNVector3 _direction;
}

@property _Bool stopped; // @synthesize stopped=_stopped;
@property float wave_height; // @synthesize wave_height=_wave_height;
@property float wave; // @synthesize wave=_wave;
@property int target_type; // @synthesize target_type=_target_type;
@property struct SCNVector3 direction; // @synthesize direction=_direction;
@property struct SCNVector3 target; // @synthesize target=_target;
@property(retain) SCNNode *shadow; // @synthesize shadow=_shadow;
@property(retain) SCNNode *arrow; // @synthesize arrow=_arrow;
@property _Bool miss; // @synthesize miss=_miss;
- (void).cxx_destruct;
- (id)init;

@end

