//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DatabaseCore.h"

@class NSMutableArray, NSMutableDictionary;

@interface ArrayDatabaseCore : DatabaseCore
{
    NSMutableDictionary *_values;
    NSMutableArray *_properties;
}

- (id)toStringWithIndention:(id)arg1;
- (id)values;
- (id)makeKey:(id)arg1;
- (void)dealloc;
- (id)initWithArrayProperties:(id)arg1;
- (id)init;

@end

