//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtobufMessage.h"

@class NSMutableArray, NSString, PlayerInsightState;

@interface AuthenticateOutput : NSObject <ProtobufMessage>
{
    int cachedSize;
    int cachedSizeId;
    _Bool showBranding;
    _Bool isSocialNetworkUser;
    _Bool isInstalledByYahoo;
    int apiSecurity;
    NSString *token;
    NSString *userId;
    NSString *gameFSRedirectMap;
    PlayerInsightState *playerInsightState;
    NSMutableArray *startDialogs;
    NSMutableArray *newPlayCodes;
    NSString *notificationClickPayload;
    NSMutableArray *deprecated1;
    NSMutableArray *apiServerHosts;
}

+ (id)authenticateOutputWithToken:(id)arg1 userId:(id)arg2 showBranding:(_Bool)arg3 gameFSRedirectMap:(id)arg4 playerInsightState:(id)arg5 startDialogs:(id)arg6 isSocialNetworkUser:(_Bool)arg7 newPlayCodes:(id)arg8 notificationClickPayload:(id)arg9 isInstalledByYahoo:(_Bool)arg10 deprecated1:(id)arg11 apiSecurity:(int)arg12 apiServerHosts:(id)arg13;
@property(retain) NSMutableArray *apiServerHosts; // @synthesize apiServerHosts;
@property int apiSecurity; // @synthesize apiSecurity;
@property(retain) NSMutableArray *deprecated1; // @synthesize deprecated1;
@property _Bool isInstalledByYahoo; // @synthesize isInstalledByYahoo;
@property(retain) NSString *notificationClickPayload; // @synthesize notificationClickPayload;
@property(retain) NSMutableArray *newPlayCodes; // @synthesize newPlayCodes;
@property _Bool isSocialNetworkUser; // @synthesize isSocialNetworkUser;
@property(retain) NSMutableArray *startDialogs; // @synthesize startDialogs;
@property(retain) PlayerInsightState *playerInsightState; // @synthesize playerInsightState;
@property(retain) NSString *gameFSRedirectMap; // @synthesize gameFSRedirectMap;
@property _Bool showBranding; // @synthesize showBranding;
@property(retain) NSString *userId; // @synthesize userId;
@property(retain) NSString *token; // @synthesize token;
- (int)sizeWithCacheId:(int)arg1;
- (void)deserializeFromReader:(id)arg1;
- (void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2;
- (id)initWithToken:(id)arg1 userId:(id)arg2 showBranding:(_Bool)arg3 gameFSRedirectMap:(id)arg4 playerInsightState:(id)arg5 startDialogs:(id)arg6 isSocialNetworkUser:(_Bool)arg7 newPlayCodes:(id)arg8 notificationClickPayload:(id)arg9 isInstalledByYahoo:(_Bool)arg10 deprecated1:(id)arg11 apiSecurity:(int)arg12 apiServerHosts:(id)arg13;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

