//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtobufMessage.h"

@class NSMutableArray, NSString;

@interface AuthenticateArgs : NSObject <ProtobufMessage>
{
    int cachedSize;
    int cachedSizeId;
    NSString *gameId;
    NSString *connectionId;
    NSMutableArray *authenticationArguments;
    NSMutableArray *playerInsightSegments;
    NSString *clientAPI;
    NSMutableArray *clientInfo;
    NSMutableArray *playCodes;
}

+ (id)authenticateArgsWithGameId:(id)arg1 connectionId:(id)arg2 authenticationArguments:(id)arg3 playerInsightSegments:(id)arg4 clientAPI:(id)arg5 clientInfo:(id)arg6 playCodes:(id)arg7;
@property(retain) NSMutableArray *playCodes; // @synthesize playCodes;
@property(retain) NSMutableArray *clientInfo; // @synthesize clientInfo;
@property(retain) NSString *clientAPI; // @synthesize clientAPI;
@property(retain) NSMutableArray *playerInsightSegments; // @synthesize playerInsightSegments;
@property(retain) NSMutableArray *authenticationArguments; // @synthesize authenticationArguments;
@property(retain) NSString *connectionId; // @synthesize connectionId;
@property(retain) NSString *gameId; // @synthesize gameId;
- (int)sizeWithCacheId:(int)arg1;
- (void)deserializeFromReader:(id)arg1;
- (void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2;
- (id)initWithGameId:(id)arg1 connectionId:(id)arg2 authenticationArguments:(id)arg3 playerInsightSegments:(id)arg4 clientAPI:(id)arg5 clientInfo:(id)arg6 playCodes:(id)arg7;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

