//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel;

@interface Banner : UIView
{
    UILabel *_adStatusLabel;
    UIImageView *_adIconImageView;
    UILabel *_adTitleLabel;
    UILabel *_adBodyLabel;
    UIButton *_adCallToActionButton;
    UIButton *_adCoverMediaView;
    UILabel *_adSocialContextLabel;
    UILabel *_sponsoredLabel;
    UIView *_adUIView;
    UIImageView *_adCover;
}

@property(retain, nonatomic) UIImageView *adCover; // @synthesize adCover=_adCover;
@property(retain, nonatomic) UIView *adUIView; // @synthesize adUIView=_adUIView;
@property(retain, nonatomic) UILabel *sponsoredLabel; // @synthesize sponsoredLabel=_sponsoredLabel;
@property(retain, nonatomic) UILabel *adSocialContextLabel; // @synthesize adSocialContextLabel=_adSocialContextLabel;
@property(retain, nonatomic) UIButton *adCoverMediaView; // @synthesize adCoverMediaView=_adCoverMediaView;
@property(retain, nonatomic) UIButton *adCallToActionButton; // @synthesize adCallToActionButton=_adCallToActionButton;
@property(retain, nonatomic) UILabel *adBodyLabel; // @synthesize adBodyLabel=_adBodyLabel;
@property(retain, nonatomic) UILabel *adTitleLabel; // @synthesize adTitleLabel=_adTitleLabel;
@property(retain, nonatomic) UIImageView *adIconImageView; // @synthesize adIconImageView=_adIconImageView;
@property(retain, nonatomic) UILabel *adStatusLabel; // @synthesize adStatusLabel=_adStatusLabel;
- (void).cxx_destruct;

@end

