//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCNView.h"

#import "SCNPhysicsContactDelegate.h"
#import "SCNSceneRendererDelegate.h"

@class BasketballBall, FeedbackGenerator, NSDate, NSMutableArray, NSMutableString, NSString, NSTimer, SCNGeometry, SCNNode, SCNPhysicsBody, SCNScene;

@interface BasketballView : SCNView <SCNPhysicsContactDelegate, SCNSceneRendererDelegate>
{
    SCNNode *pole1;
    SCNNode *pole2;
    FeedbackGenerator *feedback1;
    SCNNode *ball;
    SCNNode *basket;
    SCNNode *basket_main;
    SCNNode *net;
    SCNNode *net2;
    SCNNode *net_col;
    SCNNode *ball_shadow;
    SCNNode *selected;
    SCNPhysicsBody *selected_body;
    SCNScene *scene;
    float speed;
    float speed_x;
    struct CGPoint touch_start;
    struct CGPoint prev_pos;
    struct CGPoint touch_pos;
    struct CGPoint prev_pos2;
    struct CGVector vec;
    int last_shot;
    int last_shot2;
    int net_frame;
    NSMutableArray *balls;
    BasketballBall *game_ball;
    BasketballBall *game_ball2;
    SCNNode *count1_one;
    SCNNode *count2_one;
    SCNNode *count11;
    SCNNode *count12;
    SCNNode *count21;
    SCNNode *count22;
    SCNNode *time1;
    SCNNode *time2;
    int times1;
    int times2;
    SCNGeometry *mat2;
    NSDate *last_bounce;
    NSDate *last_rim;
    NSTimer *timer2;
    NSMutableArray *net4_textures;
    NSMutableArray *net3_textures;
    NSMutableArray *num_textures;
    NSDate *last;
    int state;
    int seed;
    int score1;
    int score2;
    int player;
    int timer;
    int times;
    float ratio;
    int time;
    NSMutableString *replay_send;
    NSDate *start_time;
    NSMutableArray *replay1;
    NSMutableArray *replay2;
    NSString *mode;
}

@property int time; // @synthesize time;
@property(retain) NSString *mode; // @synthesize mode;
@property float ratio; // @synthesize ratio;
@property int times; // @synthesize times;
@property int timer; // @synthesize timer;
@property int player; // @synthesize player;
@property(retain) NSMutableArray *replay2; // @synthesize replay2;
@property(retain) NSMutableArray *replay1; // @synthesize replay1;
@property int score2; // @synthesize score2;
@property int score1; // @synthesize score1;
@property int seed; // @synthesize seed;
@property int state; // @synthesize state;
@property(retain) NSDate *start_time; // @synthesize start_time;
@property(retain) NSMutableString *replay_send; // @synthesize replay_send;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)prefersStatusBarHidden;
- (_Bool)shouldAutorotate;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)Skip;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (void)startRound;
- (void)continueRound;
- (void)playReplay;
- (void)update;
- (void)renderer:(id)arg1 updateAtTime:(double)arg2;
- (void)spawn:(int)arg1 player:(int)arg2;
- (void)spawn:(int)arg1;
- (void)spawn;
- (void)rem:(id)arg1;
- (void)unload;
- (void)renderer:(id)arg1 willRenderScene:(id)arg2 atTime:(double)arg3;
- (void)createScene;
- (void)reset;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)changeMode:(id)arg1;
- (void)physicsWorld:(id)arg1 didUpdateContact:(id)arg2;
- (void)bounce:(float)arg1;
- (void)rim:(float)arg1;
- (void)physicsWorld:(id)arg1 didBeginContact:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

