//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCNNode;

@interface BasketballBall : NSObject
{
    _Bool hit;
    _Bool sim;
    int time;
    int shot_time;
    int player;
    SCNNode *shadow;
    SCNNode *ball;
    struct SCNVector3 pos;
    struct SCNVector3 vel;
    struct CGPoint vec;
}

@property _Bool sim; // @synthesize sim;
@property struct SCNVector3 vel; // @synthesize vel;
@property int player; // @synthesize player;
@property struct CGPoint vec; // @synthesize vec;
@property int shot_time; // @synthesize shot_time;
@property _Bool hit; // @synthesize hit;
@property int time; // @synthesize time;
@property struct SCNVector3 pos; // @synthesize pos;
@property(retain) SCNNode *ball; // @synthesize ball;
@property(retain) SCNNode *shadow; // @synthesize shadow;
- (void).cxx_destruct;
- (void)fade;
- (void)rem;
- (id)init;

@end

