//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCNNode;

@interface BeerBall : NSObject
{
    _Bool alive;
    _Bool hit;
    int time;
    int fr;
    SCNNode *shadow;
    SCNNode *ball;
    SCNNode *cup;
    struct SCNVector3 pos;
    struct SCNVector3 popo;
    struct SCNVector3 prev_position;
    struct SCNVector3 prev;
}

@property struct SCNVector3 prev; // @synthesize prev;
@property int fr; // @synthesize fr;
@property _Bool hit; // @synthesize hit;
@property struct SCNVector3 prev_position; // @synthesize prev_position;
@property _Bool alive; // @synthesize alive;
@property(retain) SCNNode *cup; // @synthesize cup;
@property struct SCNVector3 popo; // @synthesize popo;
@property int time; // @synthesize time;
@property struct SCNVector3 pos; // @synthesize pos;
@property(retain) SCNNode *ball; // @synthesize ball;
@property(retain) SCNNode *shadow; // @synthesize shadow;
- (void).cxx_destruct;
- (id)init;

@end

