//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCNView.h"

#import "SCNPhysicsContactDelegate.h"
#import "SCNSceneRendererDelegate.h"

@class BasketballBall, BeerBall, FeedbackGenerator, NSDate, NSMutableArray, NSMutableString, NSString, NSTimer, SCNGeometry, SCNMaterial, SCNNode, SCNPhysicsBody, SCNScene, SKScene;

@interface BeerView : SCNView <SCNPhysicsContactDelegate, SCNSceneRendererDelegate>
{
    SCNNode *pole1;
    SCNNode *pole2;
    SCNNode *ball;
    SCNNode *basket;
    SCNNode *basket_main;
    SCNNode *net;
    SCNNode *net2;
    SCNNode *net_col;
    SCNNode *ball_shadow;
    SCNNode *selected;
    SCNPhysicsBody *selected_body;
    SCNScene *scene;
    float speed;
    float speed_x;
    struct CGPoint touch_start;
    struct CGPoint prev_pos;
    struct CGPoint touch_pos;
    struct CGPoint prev_pos2;
    struct CGVector vec;
    int last_shot;
    int last_shot2;
    int net_frame;
    NSMutableArray *balls;
    BasketballBall *game_ball2;
    SCNNode *count11;
    SCNNode *count12;
    SCNNode *count21;
    SCNNode *count22;
    SCNNode *time1;
    SCNNode *time2;
    SCNNode *table;
    int times1;
    int times2;
    SCNGeometry *mat2;
    NSDate *last_bounce;
    NSDate *last_rim;
    NSTimer *timer2;
    NSMutableArray *net4_textures;
    NSMutableArray *net3_textures;
    NSMutableArray *num_textures;
    float px;
    float ppx;
    struct SCNVector3 ppos;
    NSMutableArray *cups;
    NSMutableArray *cups2;
    BeerBall *game_ball;
    BeerBall *ball2;
    int ball_hits;
    SCNNode *cam;
    SCNNode *cameraNode;
    NSMutableArray *rep;
    NSMutableArray *reps;
    int rep_time;
    int ball_num;
    FeedbackGenerator *feedback1;
    int rep_moves;
    NSDate *fps;
    SCNNode *touchup_cup;
    SCNNode *touchup_max_cup;
    _Bool conv;
    SCNMaterial *material1_front;
    SCNMaterial *material1_back;
    SCNMaterial *material1_rim;
    SCNMaterial *material2_front;
    SCNMaterial *material2_back;
    SCNMaterial *material2_rim;
    SCNNode *cupp2;
    _Bool mine;
    int state;
    int seed;
    int score1;
    int score2;
    int player;
    int timer;
    int times;
    float ratio;
    int time;
    int number;
    int announce;
    NSMutableString *replay_send;
    NSDate *start_time;
    NSMutableArray *replay1;
    NSMutableArray *replay2;
    NSString *mode;
    NSMutableArray *replay;
    NSString *_id;
    SKScene *_sk_scene;
}

@property(retain) SKScene *sk_scene; // @synthesize sk_scene=_sk_scene;
@property int announce; // @synthesize announce;
@property _Bool mine; // @synthesize mine;
@property int number; // @synthesize number;
@property(retain) NSString *_id; // @synthesize _id;
@property(retain) NSMutableArray *replay; // @synthesize replay;
@property int time; // @synthesize time;
@property(retain) NSString *mode; // @synthesize mode;
@property float ratio; // @synthesize ratio;
@property int times; // @synthesize times;
@property int timer; // @synthesize timer;
@property int player; // @synthesize player;
@property(retain) NSMutableArray *replay2; // @synthesize replay2;
@property(retain) NSMutableArray *replay1; // @synthesize replay1;
@property int score2; // @synthesize score2;
@property int score1; // @synthesize score1;
@property int seed; // @synthesize seed;
@property int state; // @synthesize state;
@property(retain) NSDate *start_time; // @synthesize start_time;
@property(retain) NSMutableString *replay_send; // @synthesize replay_send;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)prefersStatusBarHidden;
- (_Bool)shouldAutorotate;
- (id)exportBoard;
- (void)setBoard:(id)arg1;
- (void)overtime;
- (void)setBoard;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (float)distanceToSegment:(struct CGPoint)arg1 p2:(struct CGPoint)arg2 p3:(struct CGPoint)arg3;
- (float)projectCamera:(id)arg1 withPoint:(struct SCNVector3)arg2;
- (void)arrangeCups;
- (void)arrangeCups0;
- (void)update;
- (void)updateShadows;
- (void)updateThrow;
- (void)killCup:(id)arg1 feedback:(_Bool)arg2;
- (void)killCup:(id)arg1;
- (float)convback:(id)arg1;
- (id)conv:(float)arg1;
- (void)spawn;
- (void)spawn2;
- (void)renderer:(id)arg1 updateAtTime:(double)arg2;
- (void)rem:(id)arg1;
- (void)unload;
- (void)playReplay;
- (void)SetCupTextures;
- (void)continueGame2;
- (void)renderer:(id)arg1 didSimulatePhysicsAtTime:(double)arg2;
- (void)renderer:(id)arg1 willRenderScene:(id)arg2 atTime:(double)arg3;
- (void)continueGame;
- (void)Skip;
- (id)parseReplay:(id)arg1;
- (void)startRound;
- (void)startGame;
- (void)tes;
- (void)createScene;
- (void)displayDidRefresh3;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)changeMode:(id)arg1;
- (void)physicsWorld:(id)arg1 didUpdateContact:(id)arg2;
- (void)bounce:(float)arg1;
- (void)rim:(float)arg1;
- (void)saveGame;
- (void)physicsWorld:(id)arg1 didBeginContact:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

