//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCNNode;

@interface BeerCup : NSObject
{
    _Bool live;
    _Bool hit;
    int num;
    SCNNode *node;
    SCNNode *shadow;
    struct SCNVector3 pos;
}

@property int num; // @synthesize num;
@property _Bool hit; // @synthesize hit;
@property _Bool live; // @synthesize live;
@property(retain) SCNNode *shadow; // @synthesize shadow;
@property struct SCNVector3 pos; // @synthesize pos;
@property(retain) SCNNode *node; // @synthesize node;
- (void).cxx_destruct;
- (id)init;

@end

