//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKSpriteNode;

@interface CartCar : SKNode
{
    float vx;
    float vy;
    float slip;
    float speed;
    float rot;
    float max_speed;
    SKSpriteNode *shadow;
    SKSpriteNode *body;
}

@property float max_speed; // @synthesize max_speed;
@property(retain) SKSpriteNode *body; // @synthesize body;
@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
@property float rot; // @synthesize rot;
@property float speed; // @synthesize speed;
@property float slip; // @synthesize slip;
@property float vy; // @synthesize vy;
@property float vx; // @synthesize vx;
- (void).cxx_destruct;
- (id)init;

@end

