//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKSpriteNode.h"

@interface CartDust : SKSpriteNode
{
    float ra;
    float ss;
    float vx;
    float vy;
}

@property float vy; // @synthesize vy;
@property float vx; // @synthesize vx;
@property float ss; // @synthesize ss;
@property float ra; // @synthesize ra;
- (id)initWithImageNamed:(id)arg1;

@end

