//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKSpriteNode;

@interface CheckersTip2 : SKNode
{
    _Bool _force;
    SKSpriteNode *tip;
    struct CGPoint pos;
}

@property _Bool force; // @synthesize force=_force;
@property struct CGPoint pos; // @synthesize pos;
@property(retain) SKSpriteNode *tip; // @synthesize tip;
- (void).cxx_destruct;
- (void)blink;
- (void)unblink;
- (id)init;

@end

