//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtobufMessage.h"

@class NSString, PlayerInsightState;

@interface ConnectOutput : NSObject <ProtobufMessage>
{
    int cachedSize;
    int cachedSizeId;
    _Bool showBranding;
    NSString *token;
    NSString *userId;
    NSString *gameFSRedirectMap;
    NSString *partnerId;
    PlayerInsightState *playerInsightState;
}

+ (id)connectOutputWithToken:(id)arg1 userId:(id)arg2 showBranding:(_Bool)arg3 gameFSRedirectMap:(id)arg4 partnerId:(id)arg5 playerInsightState:(id)arg6;
@property(retain) PlayerInsightState *playerInsightState; // @synthesize playerInsightState;
@property(retain) NSString *partnerId; // @synthesize partnerId;
@property(retain) NSString *gameFSRedirectMap; // @synthesize gameFSRedirectMap;
@property _Bool showBranding; // @synthesize showBranding;
@property(retain) NSString *userId; // @synthesize userId;
@property(retain) NSString *token; // @synthesize token;
- (int)sizeWithCacheId:(int)arg1;
- (void)deserializeFromReader:(id)arg1;
- (void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2;
- (id)initWithToken:(id)arg1 userId:(id)arg2 showBranding:(_Bool)arg3 gameFSRedirectMap:(id)arg4 partnerId:(id)arg5 playerInsightState:(id)arg6;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

