//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKSpriteNode;

@interface ConnectPiece : SKNode
{
    _Bool instant;
    int player;
    float vy;
    SKSpriteNode *sprite;
    SKSpriteNode *shadow;
    SKSpriteNode *shade;
    struct CGPoint pos;
}

@property(retain) SKSpriteNode *shade; // @synthesize shade;
@property _Bool instant; // @synthesize instant;
@property float vy; // @synthesize vy;
@property struct CGPoint pos; // @synthesize pos;
@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
@property(retain) SKSpriteNode *sprite; // @synthesize sprite;
@property int player; // @synthesize player;
- (void).cxx_destruct;
- (void)setPuck:(int)arg1;
- (void)blink;
- (void)blinkWin;
- (void)unblink;
- (id)init;

@end

