//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtobufMessage.h"

@class NSMutableArray, NSString;

@interface ConnectArgs : NSObject <ProtobufMessage>
{
    int cachedSize;
    int cachedSizeId;
    NSString *gameId;
    NSString *connectionId;
    NSString *userId;
    NSString *auth;
    NSString *partnerId;
    NSMutableArray *playerInsightSegments;
    NSString *clientAPI;
    NSMutableArray *clientInfo;
}

+ (id)connectArgsWithGameId:(id)arg1 connectionId:(id)arg2 userId:(id)arg3 auth:(id)arg4 partnerId:(id)arg5 playerInsightSegments:(id)arg6 clientAPI:(id)arg7 clientInfo:(id)arg8;
@property(retain) NSMutableArray *clientInfo; // @synthesize clientInfo;
@property(retain) NSString *clientAPI; // @synthesize clientAPI;
@property(retain) NSMutableArray *playerInsightSegments; // @synthesize playerInsightSegments;
@property(retain) NSString *partnerId; // @synthesize partnerId;
@property(retain) NSString *auth; // @synthesize auth;
@property(retain) NSString *userId; // @synthesize userId;
@property(retain) NSString *connectionId; // @synthesize connectionId;
@property(retain) NSString *gameId; // @synthesize gameId;
- (int)sizeWithCacheId:(int)arg1;
- (void)deserializeFromReader:(id)arg1;
- (void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2;
- (id)initWithGameId:(id)arg1 connectionId:(id)arg2 userId:(id)arg3 auth:(id)arg4 partnerId:(id)arg5 playerInsightSegments:(id)arg6 clientAPI:(id)arg7 clientInfo:(id)arg8;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

