//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Converter : NSObject
{
}

+ (id)convertWithArray:(id)arg1 converterBlock:(CDUnknownBlockType)arg2;
+ (id)findWithList:(id)arg1 predicate:(CDUnknownBlockType)arg2;
+ (id)dictionaryFromArray:(id)arg1;
+ (id)arrayOfObjectPropertyFromDictionary:(id)arg1;
+ (id)arrayFromDictionary:(id)arg1;

@end

