//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameScene.h"

#import "PeerDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"

@class ActionButton, AvatarNode, CrazyCard, NSDate, NSMutableArray, NSMutableDictionary, NSString, PIOClient, PIOConnection, Peer, QuestionsAnswer, QuestionsAsk, SKCropNode, SKLabelNode, SKMultilineLabel, SKNode, SKSpriteNode, TipNode, UITextField, UITextView;

@interface CrazyScene : GameScene <UITextViewDelegate, UITextFieldDelegate, PeerDelegate>
{
    int time;
    SKLabelNode *connecting;
    SKSpriteNode *bg_node;
    _Bool connected;
    int state;
    int player;
    NSString *player_id1;
    NSString *player_id2;
    NSString *room_id;
    SKSpriteNode *cross;
    SKSpriteNode *line1;
    SKSpriteNode *line2;
    QuestionsAsk *ask;
    NSMutableArray *questions;
    SKMultilineLabel *tip;
    SKNode *your_word;
    SKLabelNode *word;
    SKNode *list;
    SKNode *game_screen;
    SKCropNode *crop;
    SKNode *selected;
    struct CGPoint last_touch;
    SKLabelNode *your;
    ActionButton *send;
    ActionButton *reconnect;
    SKMultilineLabel *reconnect_tip;
    NSString *answer;
    QuestionsAnswer *answer_ui;
    NSString *send_answer;
    _Bool keyboardIsShowing;
    SKSpriteNode *black;
    TipNode *wait;
    int chain;
    _Bool reverse;
    NSMutableArray *gamers;
    int game_mover;
    SKNode *crazy_menu;
    CrazyCard *crazy_card;
    NSMutableDictionary *users;
    NSMutableArray *online;
    int my_pid;
    CrazyCard *stack;
    CrazyCard *deck_stack;
    CrazyCard *deck_stack2;
    CrazyCard *deck_stack3;
    CrazyCard *deck_stack4;
    _Bool me_ready;
    UITextField *myTextField;
    CrazyCard *selected_card;
    SKNode *glow;
    SKSpriteNode *glow_glow;
    SKSpriteNode *glow_arrow;
    SKSpriteNode *glow_arrow2;
    _Bool sent;
    _Bool name_set;
    NSDate *last_sent;
    NSDate *last_received;
    _Bool last_testing;
    int last_tested;
    SKNode *settings_menu;
    SKSpriteNode *settings_black;
    SKSpriteNode *settings_settings;
    SKSpriteNode *settings_resend;
    SKSpriteNode *settings_help;
    SKCropNode *unlock_screen;
    float rot;
    int demo;
    _Bool first_load;
    _Bool premium;
    SKSpriteNode *customize_bg;
    AvatarNode *unlock_avatar1;
    AvatarNode *unlock_avatar2;
    AvatarNode *unlock_avatar3;
    AvatarNode *unlock_avatar4;
    NSDate *ping;
    Peer *multiplayer;
    UITextView *textView;
    PIOClient *client;
    PIOConnection *connection;
    SKNode *customize_ad;
}

@property(retain) SKNode *customize_ad; // @synthesize customize_ad;
@property(retain) PIOConnection *connection; // @synthesize connection;
@property(retain) PIOClient *client; // @synthesize client;
@property(retain) UITextView *textView; // @synthesize textView;
- (void).cxx_destruct;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)resize;
- (void)showAd;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)crazy8;
- (void)crazy4;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (void)update:(double)arg1;
- (void)setGameState:(int)arg1;
- (id)decryptData:(id)arg1 withKey:(id)arg2;
- (id)encryptString:(id)arg1 withKey:(id)arg2;
- (struct CGPoint)Slerp:(struct CGPoint)arg1 pos2:(struct CGPoint)arg2 ratio:(float)arg3;
- (void)sendComplete;
- (void)sendMessage;
- (void)re;
- (void)receiveMessage:(id)arg1;
- (void)sendSMS:(id)arg1;
- (int)charToInt:(id)arg1;
- (float)charToFloat:(id)arg1;
- (id)intToChar:(int)arg1;
- (id)floatToChar:(float)arg1;
- (void)handleVersion:(id)arg1;
- (_Bool)canShowAd;
- (void)handleGameOver;
- (void)handleGameOver:(id)arg1;
- (void)winner;
- (void)handleMove:(id)arg1;
- (void)whip;
- (void)handleName:(id)arg1;
- (void)hideSettings;
- (void)cardSound;
- (void)handleDisconnect:(id)arg1;
- (void)doReconnect;
- (void)sortCards:(id)arg1;
- (void)setCards:(id)arg1 cards:(id)arg2;
- (void)handleGameStart:(id)arg1;
- (void)handleMsg:(id)arg1;
- (void)handleLeft:(id)arg1;
- (void)handleGameList:(id)arg1;
- (void)handleNotReady:(id)arg1;
- (void)handleReady:(id)arg1;
- (void)doReady;
- (void)reloadAd;
- (void)handleJoinList:(id)arg1;
- (void)handleJoin:(id)arg1;
- (void)unload;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)showMenu;
- (void)showSMS;
- (void)createSceneContents;
- (float)brightness:(id)arg1;
- (void)updateUnlock;
- (void)getUsername:(id)arg1;
- (void)didMoveToView:(id)arg1;
- (id)initWithMain:(id)arg1 msg:(id)arg2;
- (void)PeerFailed:(id)arg1 code:(int)arg2;
- (void)PeerMessage:(id)arg1 data:(id)arg2;
- (void)PeerDisconnected:(id)arg1;
- (void)PeerConnected:(id)arg1;
- (void)PeerGateConnected:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

