//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AvatarNode, NSMutableArray, NSString, PokerChat, SKLabelNode, SKNode, SKSpriteNode;

@interface CrazyPlayer : NSObject
{
    _Bool ready;
    _Bool live;
    int id2;
    int dir;
    SKNode *avatar;
    NSString *nick;
    AvatarNode *avatar2;
    SKLabelNode *nickname;
    SKLabelNode *ready_label;
    NSMutableArray *cards;
    SKSpriteNode *bg;
    PokerChat *chat;
}

@property(retain) PokerChat *chat; // @synthesize chat;
@property(retain) SKSpriteNode *bg; // @synthesize bg;
@property int dir; // @synthesize dir;
@property _Bool live; // @synthesize live;
@property(retain) NSMutableArray *cards; // @synthesize cards;
@property(retain) SKLabelNode *ready_label; // @synthesize ready_label;
@property(retain) SKLabelNode *nickname; // @synthesize nickname;
@property(retain) AvatarNode *avatar2; // @synthesize avatar2;
@property _Bool ready; // @synthesize ready;
@property(retain) NSString *nick; // @synthesize nick;
@property int id2; // @synthesize id2;
@property(retain) SKNode *avatar; // @synthesize avatar;
- (void).cxx_destruct;
- (void)gameState;
- (void)lobbyState;
- (id)init;

@end

