//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKScene.h"

#import "SKStoreProductViewControllerDelegate.h"

@class NSString, SKButton, SKNode, UIViewController;

@interface CreditsScene : SKScene <SKStoreProductViewControllerDelegate>
{
    SKNode *screen;
    SKNode *contributions;
    SKNode *other;
    SKNode *created;
    SKButton *icon1;
    SKButton *icon2;
    SKButton *link;
    _Bool landscape;
    struct CGSize stageSize;
    float ratio;
    SKNode *selected;
    UIViewController *vc;
}

- (void).cxx_destruct;
- (void)resize;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (id)playSound:(id)arg1;
- (void)buttonCancel;
- (void)buttonDown;
- (void)buttonUp;
- (void)Link;
- (void)Domino;
- (void)Solitaire;
- (void)didMoveToView:(id)arg1;
- (void)setMain:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

