//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface CurveToSegments : NSObject
{
    int m_count;
    float m_distance_tolerance;
    float m_approximation_scale;
    float curve_recursion_limit;
    float curve_distance_epsilon;
    float curve_collinearity_epsilon;
    float curve_angle_tolerance_epsilon;
    float m_angle_tolerance;
    NSMutableArray *m_points;
}

@property(retain) NSMutableArray *m_points; // @synthesize m_points;
- (void).cxx_destruct;
- (void)bezier:(struct CGPoint)arg1 p2:(struct CGPoint)arg2 p3:(struct CGPoint)arg3;
- (void)recursive_bezier:(struct CGPoint)arg1 p2:(struct CGPoint)arg2 p3:(struct CGPoint)arg3 level:(int)arg4;
- (id)init:(struct CGPoint)arg1 p2:(struct CGPoint)arg2 p3:(struct CGPoint)arg3;

@end

