//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CustomEncryption : NSObject
{
}

+ (id)DecryptBase64String:(id)arg1 key:(id)arg2 iv:(id)arg3;
+ (id)EncryptBase64String:(id)arg1 key:(id)arg2 iv:(id)arg3;
+ (id)AES256DecryptWithData:(id)arg1 Key:(id)arg2 IV:(id)arg3;
+ (id)AES256EncryptWithData:(id)arg1 Key:(id)arg2 IV:(id)arg3;

@end

