//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCNNode;

@interface DartsDart : NSObject
{
    _Bool _miss;
    _Bool _shot;
    _Bool _stopped;
    int _score;
    int _full_score;
    int _multi;
    int _anim;
    int _state;
    int _target_type;
    float _wave;
    float _wave_height;
    float _rotation_speed;
    SCNNode *_dart;
    SCNNode *_shadow;
    struct SCNVector3 _origin;
    struct SCNVector3 _target;
    struct SCNVector3 _direction;
}

@property float rotation_speed; // @synthesize rotation_speed=_rotation_speed;
@property _Bool stopped; // @synthesize stopped=_stopped;
@property float wave_height; // @synthesize wave_height=_wave_height;
@property float wave; // @synthesize wave=_wave;
@property int target_type; // @synthesize target_type=_target_type;
@property struct SCNVector3 direction; // @synthesize direction=_direction;
@property struct SCNVector3 target; // @synthesize target=_target;
@property struct SCNVector3 origin; // @synthesize origin=_origin;
@property(retain) SCNNode *shadow; // @synthesize shadow=_shadow;
@property(retain) SCNNode *dart; // @synthesize dart=_dart;
@property int state; // @synthesize state=_state;
@property int anim; // @synthesize anim=_anim;
@property _Bool shot; // @synthesize shot=_shot;
@property int multi; // @synthesize multi=_multi;
@property int full_score; // @synthesize full_score=_full_score;
@property int score; // @synthesize score=_score;
@property _Bool miss; // @synthesize miss=_miss;
- (void).cxx_destruct;
- (id)init;

@end

