//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameScene.h"

@class DartsView, NSDate, NSMutableArray, NSMutableString, NSString, SKLabelNode, SKNode, SKShapeNode, SKSpriteNode;

@interface DartsScene : GameScene
{
    _Bool sent;
    NSMutableString *replay_send;
    NSMutableArray *replay;
    int player2;
    NSString *player_id1;
    NSString *player_id2;
    NSString *mode;
    SKNode *scoreboard1;
    SKNode *scoreboard2;
    SKLabelNode *scoreboard_score1;
    SKLabelNode *scoreboard_score2;
    SKSpriteNode *ui_dart1;
    SKSpriteNode *ui_dart2;
    SKSpriteNode *ui_dart3;
    SKNode *ui_darts;
    float score_display1;
    float score_display2;
    NSDate *counter_date;
    SKNode *win_tip;
    SKSpriteNode *win_tip_node;
    SKLabelNode *win_tip_score;
    SKLabelNode *win_tip_win;
    int time;
    SKSpriteNode *bg_node;
    SKNode *selected;
    SKShapeNode *_spinnyNode;
    SKLabelNode *_label;
    int score1;
    int score2;
    int darts_num;
    int state;
    int player;
    int style1;
    int style2;
    int _start_score;
    float _ratio;
    DartsView *scene3d;
}

@property float ratio; // @synthesize ratio=_ratio;
@property int start_score; // @synthesize start_score=_start_score;
@property int style2; // @synthesize style2;
@property int style1; // @synthesize style1;
@property int player; // @synthesize player;
@property int state; // @synthesize state;
@property int darts_num; // @synthesize darts_num;
@property int score2; // @synthesize score2;
@property int score1; // @synthesize score1;
@property(retain) DartsView *scene3d; // @synthesize scene3d;
- (void).cxx_destruct;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)unload;
- (void)resize;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (struct CGPoint)Slerp:(struct CGPoint)arg1 pos2:(struct CGPoint)arg2 ratio:(float)arg3;
- (void)update:(double)arg1;
- (void)saveMove:(struct CGPoint)arg1 type:(int)arg2;
- (void)shoot:(struct CGPoint)arg1;
- (void)shoot;
- (void)playCounter2;
- (void)playCounter;
- (void)sendMessage;
- (void)endMove:(int)arg1 full_score:(int)arg2 multi:(int)arg3 pos:(struct CGPoint)arg4 send_pos:(struct CGPoint)arg5;
- (void)showScore2:(int)arg1 full_score:(int)arg2 multi:(int)arg3 pos:(struct CGPoint)arg4 send_pos:(struct CGPoint)arg5;
- (void)showScore:(int)arg1 full_score:(int)arg2 multi:(int)arg3 pos:(struct CGPoint)arg4 send_pos:(struct CGPoint)arg5;
- (void)sco2;
- (void)sco;
- (void)setTip;
- (void)spawnDart;
- (void)newRound;
- (void)newGame;
- (id)parseReplay:(id)arg1;
- (void)playReplay;
- (void)receiveMessage:(id)arg1;
- (void)createSceneContents;
- (void)didMoveToView:(id)arg1;
- (void)impact;
- (id)getScreen;
- (id)initWithMain:(id)arg1 msg:(id)arg2;

@end

