//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet;

@interface DatabaseCore : NSObject
{
    NSMutableSet *_dirty;
    _Bool inObjectGraph;
}

@property _Bool inObjectGraph; // @synthesize inObjectGraph;
- (void)setValueFromValueObject:(id)arg1 forKey:(id)arg2;
- (id)getCore:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (_Bool)deepExists:(id)arg1;
- (id)deepAction:(id)arg1 index:(int)arg2 action:(int)arg3 setValue:(id)arg4;
- (id)performDeepAction:(id)arg1 action:(int)arg2 value:(id)arg3;
- (id)deepSet:(id)arg1 value:(id)arg2;
- (id)deepGet:(id)arg1 throwOnMissing:(_Bool)arg2;
- (void)clear;
- (id)allValues;
- (id)toStringWithIndention:(id)arg1;
- (id)makeKey:(id)arg1;
- (id)values;
- (void)clearDirty:(id)arg1;
- (_Bool)isDirty:(id)arg1;
- (void)setDirty:(id)arg1;
- (id)dirty;
- (void)dealloc;
- (id)init;

@end

