//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKSpriteNode;

@interface DotsLine : SKNode
{
    SKSpriteNode *sprite;
    int type;
    int player;
    struct CGPoint pos;
    struct CGPoint start;
    struct CGPoint finish;
}

@property int player; // @synthesize player;
@property struct CGPoint finish; // @synthesize finish;
@property struct CGPoint start; // @synthesize start;
@property int type; // @synthesize type;
@property struct CGPoint pos; // @synthesize pos;
- (void).cxx_destruct;
- (void)Play;
- (void)PrePlay;
- (void)blink;
- (void)SetPlayer:(int)arg1;
- (id)init;

@end

