//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class DotsLine;

@interface DotsSquare : SKNode
{
    DotsLine *line1;
    DotsLine *line2;
    int player;
    struct CGPoint pos;
}

@property struct CGPoint pos; // @synthesize pos;
@property int player; // @synthesize player;
- (void).cxx_destruct;
- (void)Play2;
- (void)Play1;
- (void)Play;
- (void)SetPlayer:(int)arg1;
- (id)init;

@end

