//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AVAudioPlayer.h"

@interface ExtendedAVAudioPlayer : AVAudioPlayer
{
    double _relativeVolume;
    double _currentRelativeVolume;
    unsigned long long _type;
}

@property unsigned long long type; // @synthesize type=_type;
@property double currentRelativeVolume; // @synthesize currentRelativeVolume=_currentRelativeVolume;
@property(nonatomic) double relativeVolume; // @synthesize relativeVolume=_relativeVolume;
- (id)initWithContentsOfURL:(id)arg1 error:(id *)arg2;
- (void)setVolume:(float)arg1;

@end

