//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImpactFeedbackGenerator, UISelectionFeedbackGenerator;

@interface FeedbackGenerator : NSObject
{
    UIImpactFeedbackGenerator *impact_feedback;
    UISelectionFeedbackGenerator *selection_feedback;
    int type;
}

- (void).cxx_destruct;
- (void)impactOccurred;
- (void)selectionChanged;
- (void)prepare;
- (id)initWithType:(int)arg1;

@end

