//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GAReachability, NSNumber, NSString;

@interface GADevice : NSObject
{
    GAReachability *_hostReachability;
    NSString *_osPlatform;
    NSString *_osVersion;
    NSString *_deviceModel;
    NSString *_deviceMake;
    NSString *_connectionType;
    NSNumber *_jailBroken;
    NSNumber *_limitedAdTracking;
    NSNumber *_testflightBuild;
    NSNumber *_zeroIdfa;
}

+ (_Bool)deviceIsLowerOrEqualToIos6;
+ (_Bool)isZeroIdfa;
+ (_Bool)isTestflightBuild;
+ (_Bool)isJailbroken;
+ (_Bool)isLimitedAdTracking;
+ (id)getBundleIdentifier;
+ (id)idfv;
+ (id)idfa;
+ (id)connectionType;
+ (id)deviceMake;
+ (id)deviceModel;
+ (id)osVersion;
+ (id)osPlatform;
+ (void)setSharedInstance:(id)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSNumber *zeroIdfa; // @synthesize zeroIdfa=_zeroIdfa;
@property(retain, nonatomic) NSNumber *testflightBuild; // @synthesize testflightBuild=_testflightBuild;
@property(retain, nonatomic) NSNumber *limitedAdTracking; // @synthesize limitedAdTracking=_limitedAdTracking;
@property(retain, nonatomic) NSNumber *jailBroken; // @synthesize jailBroken=_jailBroken;
@property(retain, nonatomic) NSString *connectionType; // @synthesize connectionType=_connectionType;
@property(retain, nonatomic) NSString *deviceMake; // @synthesize deviceMake=_deviceMake;
@property(retain, nonatomic) NSString *deviceModel; // @synthesize deviceModel=_deviceModel;
@property(retain, nonatomic) NSString *osVersion; // @synthesize osVersion=_osVersion;
@property(retain, nonatomic) NSString *osPlatform; // @synthesize osPlatform=_osPlatform;
@property(retain, nonatomic) GAReachability *hostReachability; // @synthesize hostReachability=_hostReachability;
- (void).cxx_destruct;
- (void)reachabilityChanged:(id)arg1;
- (void)dealloc;
- (id)init;
- (_Bool)isRunningInTestFlightEnvironment;
- (_Bool)hasEmbeddedMobileProvision;
- (_Bool)isAppStoreReceiptSandbox;
- (_Bool)checkJailbroken;
- (id)getConnectionType;
- (id)getDeviceMake;
- (id)getDeviceModel;
- (id)getOsVersion;
- (id)getOsPlatform;

@end

