//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GAHelpers : NSObject
{
}

+ (id)gzipDeflateWithData:(id)arg1;
+ (id)gzipEnflateWithData:(id)arg1;
+ (_Bool)stringMatchWithString:(id)arg1 andPattern:(id)arg2;
+ (id)dictionaryWithJsonData:(id)arg1;
+ (id)dictionaryWithJsonString:(id)arg1;
+ (id)jsonStringWithObject:(id)arg1;
+ (id)escapeValueForURLParameter:(id)arg1;
+ (id)querystringWithDictionary:(id)arg1;
+ (id)hmacWithKey:(id)arg1 andData:(id)arg2;
+ (id)sha256HashForData:(id)arg1;
+ (id)base64forData:(id)arg1;
+ (id)encryptString:(id)arg1 withKey:(id)arg2;
+ (id)dataToMd5:(id)arg1;
+ (id)stringToMd5:(id)arg1;
+ (id)generateUUID;

@end

