//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURLRequest, NSURLSession, NSURLSessionDataTask;

@interface GAHTTPSessionDataTask : NSObject
{
    NSURLRequest *_request;
    NSURLSession *_session;
    NSURLSessionDataTask *_dataTask;
    CDUnknownBlockType _onSuccess;
    CDUnknownBlockType _onFailure;
    CDUnknownBlockType _onProgress;
}

@property(copy, nonatomic) CDUnknownBlockType onProgress; // @synthesize onProgress=_onProgress;
@property(copy, nonatomic) CDUnknownBlockType onFailure; // @synthesize onFailure=_onFailure;
@property(copy, nonatomic) CDUnknownBlockType onSuccess; // @synthesize onSuccess=_onSuccess;
@property(retain, nonatomic) NSURLSessionDataTask *dataTask; // @synthesize dataTask=_dataTask;
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cancelSessionAndTask;
- (void)cancelSessionAndTask:(_Bool)arg1;
- (void)performRequestWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2 progress:(CDUnknownBlockType)arg3;
- (id)initWithRequest:(id)arg1;

@end

