//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GAHTTPApi : NSObject
{
    _Bool _useGzip;
    NSString *_httpProtocol;
    NSString *_hostname;
    NSString *_port;
    NSString *_version;
    NSString *_baseUrl;
    NSString *_initializeUrlPath;
    NSString *_eventsUrlPath;
}

+ (void)setSharedInstance:(id)arg1;
+ (id)sharedInstance;
@property(nonatomic) _Bool useGzip; // @synthesize useGzip=_useGzip;
@property(retain) NSString *eventsUrlPath; // @synthesize eventsUrlPath=_eventsUrlPath;
@property(retain) NSString *initializeUrlPath; // @synthesize initializeUrlPath=_initializeUrlPath;
@property(retain) NSString *baseUrl; // @synthesize baseUrl=_baseUrl;
@property(retain) NSString *version; // @synthesize version=_version;
@property(retain) NSString *port; // @synthesize port=_port;
@property(retain) NSString *hostname; // @synthesize hostname=_hostname;
@property(retain) NSString *httpProtocol; // @synthesize httpProtocol=_httpProtocol;
- (void).cxx_destruct;
- (long long)requestItunesInfoReturningDict:(id *)arg1 withBundleId:(id)arg2;
- (long long)processRequestResponse:(id)arg1 withResponse:(id)arg2 andError:(id)arg3 withRequestId:(id)arg4;
- (id)createGETRequestWithUrl:(id)arg1;
- (id)createRequestWithPayload:(id)arg1 andUrl:(id)arg2 usingGzip:(_Bool)arg3;
- (id)makeRequestAuthSha256Hash:(id)arg1;
- (id)validateAndCleanInitRequestResponse:(id)arg1;
- (id)getApiHostname;
- (void)sendSdkErrorEventWithFormData:(id)arg1 andSuccessCallback:(CDUnknownBlockType)arg2 andErrorCallback:(CDUnknownBlockType)arg3;
- (long long)sendEventsInArray:(id)arg1 ReturningDict:(id *)arg2;
- (long long)requestInitReturningDict:(id *)arg1;
- (id)init;

@end

