//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GALogger : NSObject
{
    _Bool _verboseLogEnabled;
    _Bool _orbitLogEnabled;
    _Bool _analyticsLogEnabled;
    _Bool _debugEnabled;
}

+ (void)sendNotificationMessage:(id)arg1 ofType:(long long)arg2;
+ (void)ii:(long long)arg1 format:(id)arg2;
+ (void)i:(long long)arg1 format:(id)arg2;
+ (void)d:(long long)arg1 format:(id)arg2;
+ (void)e:(long long)arg1 format:(id)arg2;
+ (void)w:(long long)arg1 format:(id)arg2;
+ (id)getMessageTagForDomain:(long long)arg1;
+ (void)setVerboseLog:(_Bool)arg1;
+ (void)setOrbitLog:(_Bool)arg1;
+ (void)setAnalyticsLog:(_Bool)arg1;
+ (void)setSharedInstance:(id)arg1;
+ (id)sharedInstance;
@property(nonatomic) _Bool debugEnabled; // @synthesize debugEnabled=_debugEnabled;
@property(nonatomic) _Bool analyticsLogEnabled; // @synthesize analyticsLogEnabled=_analyticsLogEnabled;
@property(nonatomic) _Bool orbitLogEnabled; // @synthesize orbitLogEnabled=_orbitLogEnabled;
@property(nonatomic) _Bool verboseLogEnabled; // @synthesize verboseLogEnabled=_verboseLogEnabled;
- (id)init;

@end

