//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface GameConfiguration : NSObject
{
    _Bool _dynamic_preview;
    _Bool _cache_preview;
    _Bool _custom_captions;
    _Bool _ads_enabled;
    _Bool _ads_rare;
    _Bool _multiplayer;
    int _min_players;
    NSString *_game_id;
    NSMutableDictionary *_mode_previews;
}

@property _Bool multiplayer; // @synthesize multiplayer=_multiplayer;
@property int min_players; // @synthesize min_players=_min_players;
@property _Bool ads_rare; // @synthesize ads_rare=_ads_rare;
@property _Bool ads_enabled; // @synthesize ads_enabled=_ads_enabled;
@property _Bool custom_captions; // @synthesize custom_captions=_custom_captions;
@property _Bool cache_preview; // @synthesize cache_preview=_cache_preview;
@property _Bool dynamic_preview; // @synthesize dynamic_preview=_dynamic_preview;
@property(retain) NSMutableDictionary *mode_previews; // @synthesize mode_previews=_mode_previews;
@property(retain) NSString *game_id; // @synthesize game_id=_game_id;
- (void).cxx_destruct;
- (id)init;

@end

