//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AVAudioPlayer, NSMutableArray;

@interface GameSettings : UIView
{
    AVAudioPlayer *button_down;
    AVAudioPlayer *button_up;
    AVAudioPlayer *button_cancel;
    NSMutableArray *options;
}

@property(retain) NSMutableArray *options; // @synthesize options;
- (void).cxx_destruct;
- (void)setSounds:(id)arg1 up:(id)arg2 cancel:(id)arg3;
- (void)resize;
- (void)update;
- (id)initWithFrame:(struct CGRect)arg1;

@end

