//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ALAdDisplayDelegate.h"
#import "ALAdLoadDelegate.h"
#import "ALNativeAdLoadDelegate.h"
#import "ALNativeAdPrecacheDelegate.h"
#import "MPAdViewDelegate.h"
#import "MPInterstitialAdControllerDelegate.h"
#import "MPNativeAdDelegate.h"
#import "UITextFieldDelegate.h"

@class ALCarouselCardView, ALCarouselMediaView, ALNativeAd, Banner, CADisplayLink, CHAd, FullscreenAdContainer, MPAdView, MPInterstitialAdController, MPNativeAd, MPNativeAdViewTemplate, MSMessage, MessagesViewController, NSDate, NSMutableArray, NSString, NSTimer, SCNView, SKScene, SKView, UIButton, UIImageView, UILabel, UIScrollView, UITextField, UIView;

@interface GameViewController : UIViewController <ALNativeAdLoadDelegate, ALNativeAdPrecacheDelegate, UITextFieldDelegate, ALAdLoadDelegate, ALAdDisplayDelegate, MPNativeAdDelegate, MPInterstitialAdControllerDelegate, MPAdViewDelegate>
{
    UIView *menu_tint;
    UIView *menu;
    UIView *ad_spinner;
    _Bool chad_shown;
    CHAd *chad;
    UILabel *label;
    SKView *skView;
    MSMessage *msg;
    ALCarouselMediaView *med;
    ALCarouselCardView *card;
    UIView *hzwrapper;
    UIImageView *hzimage;
    Banner *banner;
    UIViewController *adVC;
    MPInterstitialAdController *mpInterstitial;
    MPNativeAdViewTemplate *mpNativeAdView;
    MPNativeAd *mpNativeAd;
    MPAdView *mpAdView;
    UIView *mpContainer;
    NSMutableArray *waterfall;
    UIView *tint;
    _Bool shown;
    UIView *sms;
    UITextField *sms_text;
    UIView *sms_padding;
    UIScrollView *sms_transcript;
    NSMutableArray *sms_messages;
    UIButton *sms_button;
    struct CGSize keyboard_size;
    _Bool keyboard;
    _Bool chat;
    _Bool rendering_ad;
    ALNativeAd *al_banner;
    _Bool chat_enabled;
    _Bool ch_started;
    int ad_requests;
    CADisplayLink *displayLink;
    NSDate *fps;
    NSDate *fps2;
    int fps_count;
    float last_fps;
    NSDate *ad_started;
    int ad_time;
    _Bool new_ads;
    FullscreenAdContainer *fullscreenContainer;
    _Bool sending;
    _Bool unloaded;
    MessagesViewController *main;
    SKScene *scene;
    NSTimer *timer;
    SCNView *scnView;
    NSTimer *timer2;
}

@property __weak NSTimer *timer2; // @synthesize timer2;
@property(retain) SCNView *scnView; // @synthesize scnView;
@property _Bool unloaded; // @synthesize unloaded;
@property __weak NSTimer *timer; // @synthesize timer;
@property(retain) SKScene *scene; // @synthesize scene;
@property _Bool sending; // @synthesize sending;
@property __weak MessagesViewController *main; // @synthesize main;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)didReceiveMessage:(id)arg1;
- (_Bool)sameSession:(id)arg1;
- (id)getId:(id)arg1;
- (void)buttonPressed:(id)arg1;
- (id)getMessage;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (id)playSound:(id)arg1 volume:(float)arg2;
- (void)showSend;
- (void)displayDidRefresh2;
- (void)displayDidRefresh:(id)arg1;
- (void)refreshScreen;
- (void)displayDidRefresh3;
- (id)getPreview;
- (void)viewDidLoad;
- (void)avatarsUnlocked;
- (void)cleanUp2:(id)arg1;
- (void)cleanUp:(id)arg1;
- (_Bool)sendLive;
- (_Bool)getReduce;
- (void)unload;
- (void)getUsername:(id)arg1;
- (void)receiveMessage:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)isReady;
- (void)handleSingleTap:(id)arg1;
- (void)renderAd:(id)arg1;
- (void)launchClickTarget;
- (void)didTapCTAButton:(id)arg1;
- (_Bool)checkString:(id)arg1;
- (void)trackImpression:(id)arg1;
- (void)nativeAdService:(id)arg1 didLoadAds:(id)arg2;
- (void)nativeAdService:(id)arg1 didFailToPrecacheImagesForAd:(id)arg2 withError:(long long)arg3;
- (void)nativeAdService:(id)arg1 didFailToPrecacheVideoForAd:(id)arg2 withError:(long long)arg3;
- (void)nativeAdService:(id)arg1 didFailToLoadAdsWithError:(long long)arg2;
- (void)nativeAdService:(id)arg1 didPrecacheVideoForAd:(id)arg2;
- (void)nativeAdService:(id)arg1 didPrecacheImagesForAd:(id)arg2;
- (void)displayMPNativeAd;
- (void)adViewDidLoadAd:(id)arg1;
- (void)layoutFullscreenad;
- (void)displayAdFullscreen:(id)arg1;
- (void)skipAd:(id)arg1;
- (void)skipAd;
- (void)readyForAd;
- (void)adViewDidFailToLoadAd:(id)arg1;
- (void)willLeaveApplicationFromNativeAd:(id)arg1;
- (void)willPresentModalForNativeAd:(id)arg1;
- (void)willLeaveApplicationFromAd:(id)arg1;
- (void)willPresentModalViewForAd:(id)arg1;
- (void)nativeAdWasClosed;
- (void)tt2:(id)arg1;
- (void)adDisplayed;
- (void)mpNative:(id)arg1;
- (void)mpMrect:(id)arg1;
- (void)interstitialDidFailToLoadAd:(id)arg1;
- (void)interstitialDidLoadAd:(id)arg1;
- (void)showInterstitial;
- (void)showInt:(id)arg1;
- (void)showAd:(id)arg1 force:(_Bool)arg2;
- (void)showAd:(id)arg1;
- (void)downWaterfall;
- (void)showAd;
- (id)viewControllerForPresentingModalView;
- (void)adjustAd;
- (void)update;
- (_Bool)prefersHomeIndicatorAutoHidden;
- (void)stopTimer;
- (void)startTimer:(id)arg1;
- (void)hideAd:(_Bool)arg1;
- (void)hideAd;
- (void)unfadeAd;
- (void)fadeAd;
- (void)viewDidLayoutSubviews;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)keyboardWasShown:(id)arg1;
- (void)keyboardChangeFrame:(id)arg1;
- (void)registerForKeyboardNotifications;
- (void)sendSMS;
- (void)receivedSMS:(id)arg1 from:(id)arg2;
- (void)tapTransctipt;
- (void)lay;
- (void)viewWillLayoutSubviews;
- (void)hideSMS;
- (void)showSMS;
- (void)focusSMS;
- (void)initSMS;
- (id)initWithMain:(id)arg1 msg:(id)arg2;
- (void)resetWaterfall;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

