//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FABKit.h"

@class NSString;

@interface GameAnalytics : NSObject <FABKit>
{
}

+ (void)initializeIfNeeded;
+ (id)kitBuildVersion;
+ (id)kitDisplayVersion;
+ (id)bundleIdentifier;
+ (void)setEnableDebugLog:(_Bool)arg1;
+ (void)setBaseUrl:(id)arg1;
+ (void)setBirthYear:(long long)arg1;
+ (void)setGender:(id)arg1;
+ (void)setFacebookId:(id)arg1;
+ (void)setCustomDimension03:(id)arg1;
+ (void)setCustomDimension02:(id)arg1;
+ (void)setCustomDimension01:(id)arg1;
+ (void)endSession;
+ (void)startSession;
+ (void)setEnabledManualSessionHandling:(_Bool)arg1;
+ (void)setEnabledVerboseLog:(_Bool)arg1;
+ (void)setEnabledInfoLog:(_Bool)arg1;
+ (_Bool)isSdkReadyWithNeedsInitialized:(_Bool)arg1 andWarn:(_Bool)arg2 andMessage:(id)arg3;
+ (_Bool)isSdkReadyWithNeedsInitialized:(_Bool)arg1 andWarn:(_Bool)arg2;
+ (_Bool)isSdkReadyWithNeedsInitialized:(_Bool)arg1;
+ (void)addErrorEventWithSeverity:(long long)arg1 message:(id)arg2;
+ (void)addDesignEventWithEventId:(id)arg1 value:(id)arg2;
+ (void)addDesignEventWithEventId:(id)arg1;
+ (void)addProgressionEventWithProgressionStatus:(long long)arg1 progression01:(id)arg2 progression02:(id)arg3 progression03:(id)arg4 score:(long long)arg5;
+ (void)addProgressionEventWithProgressionStatus:(long long)arg1 progression01:(id)arg2 progression02:(id)arg3 progression03:(id)arg4;
+ (void)addResourceEventWithFlowType:(long long)arg1 currency:(id)arg2 amount:(id)arg3 itemType:(id)arg4 itemId:(id)arg5;
+ (void)addBusinessEventWithCurrency:(id)arg1 amount:(long long)arg2 itemType:(id)arg3 itemId:(id)arg4 cartType:(id)arg5 receipt:(id)arg6 getReceiptAutomatically:(_Bool)arg7;
+ (void)addBusinessEventWithCurrency:(id)arg1 amount:(long long)arg2 itemType:(id)arg3 itemId:(id)arg4 cartType:(id)arg5 receipt:(id)arg6;
+ (void)addBusinessEventWithCurrency:(id)arg1 amount:(long long)arg2 itemType:(id)arg3 itemId:(id)arg4 cartType:(id)arg5 autoFetchReceipt:(_Bool)arg6;
+ (void)initializeAfterGameKeysAreSet;
+ (void)initializeWithConfiguredGameKeyAndGameSecret;
+ (void)initializeWithGameKey:(id)arg1 gameSecret:(id)arg2;
+ (void)configureGameKey:(id)arg1 gameSecret:(id)arg2;
+ (void)configureAvailableResourceItemTypes:(id)arg1;
+ (void)configureAvailableResourceCurrencies:(id)arg1;
+ (void)configureAvailableCustomDimensions03:(id)arg1;
+ (void)configureAvailableCustomDimensions02:(id)arg1;
+ (void)configureAvailableCustomDimensions01:(id)arg1;
+ (void)configureEngineVersion:(id)arg1;
+ (void)configureSdkVersion:(id)arg1;
+ (void)configureUserId:(id)arg1;
+ (void)configureBuild:(id)arg1;
+ (void)initialize;
+ (id)sharedInstance;
+ (_Bool)internalInitialize;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

