//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SKStoreProductViewControllerDelegate.h"
#import "UIScrollViewDelegate.h"

@class AVAudioPlayer, BackButton, GameIcon, GameSettings, MessagesViewController, NSMutableArray, NSString, NSTimer, SKScene, SKView, UICollectionView, UIImageView, UILabel, UIScrollView, UIView, UIViewButton;

@interface GamesViewController : UIViewController <UIScrollViewDelegate, SKStoreProductViewControllerDelegate>
{
    UILabel *games_label;
    UILabel *top_ui_store;
    UILabel *top_ui_settings;
    UIView *alert;
    UIView *folder_view;
    UIView *folder_view_rect;
    UIView *folder_view_bg;
    UIImageView *folder_view_close;
    UIImageView *newicon;
    UIImageView *top_shade;
    UICollectionView *_collectionView;
    NSMutableArray *grid;
    NSMutableArray *folder_grid;
    UIScrollView *scroll;
    int cells;
    float gap;
    float top_gap;
    BackButton *back_button;
    UIImageView *bg;
    _Bool just_started;
    float ratio2;
    float ratio4;
    float ratio3;
    SKView *skView;
    AVAudioPlayer *button_down;
    AVAudioPlayer *button_up;
    AVAudioPlayer *button_cancel;
    int wins;
    _Bool show_settings;
    _Bool first_tap;
    UIImageView *play_but;
    _Bool scrolling;
    _Bool keyboardIsShowing;
    NSString *lang;
    NSTimer *timer;
    MessagesViewController *main;
    GameSettings *settings;
    SKScene *scene;
    GameIcon *selected;
    UIView *_top_ui;
    UIImageView *_top_shadow;
    UIView *_top_ui_mainmenu;
    UIViewButton *_top_ui_play_button;
    UIViewButton *_top_ui_title;
    UILabel *_top_ui_title_label;
    UIViewButton *_top_ui_games;
    UIViewButton *_top_ui_settings;
    UIViewButton *_top_ui_store;
    UIView *_top_ui_line1;
    UIView *_top_ui_line2;
}

@property(retain) UIView *top_ui_line2; // @synthesize top_ui_line2=_top_ui_line2;
@property(retain) UIView *top_ui_line1; // @synthesize top_ui_line1=_top_ui_line1;
@property(retain) UIViewButton *top_ui_store; // @synthesize top_ui_store=_top_ui_store;
@property(retain) UIViewButton *top_ui_settings; // @synthesize top_ui_settings=_top_ui_settings;
@property(retain) UIViewButton *top_ui_games; // @synthesize top_ui_games=_top_ui_games;
@property(retain) UILabel *top_ui_title_label; // @synthesize top_ui_title_label=_top_ui_title_label;
@property(retain) UIViewButton *top_ui_title; // @synthesize top_ui_title=_top_ui_title;
@property(retain) UIViewButton *top_ui_play_button; // @synthesize top_ui_play_button=_top_ui_play_button;
@property(retain) UIView *top_ui_mainmenu; // @synthesize top_ui_mainmenu=_top_ui_mainmenu;
@property(retain) UIImageView *top_shadow; // @synthesize top_shadow=_top_shadow;
@property(retain) UIView *top_ui; // @synthesize top_ui=_top_ui;
@property _Bool keyboardIsShowing; // @synthesize keyboardIsShowing;
@property(retain) GameIcon *selected; // @synthesize selected;
@property _Bool scrolling; // @synthesize scrolling;
@property(retain) SKScene *scene; // @synthesize scene;
@property(retain) GameSettings *settings; // @synthesize settings;
@property __weak MessagesViewController *main; // @synthesize main;
@property __weak NSTimer *timer; // @synthesize timer;
@property(retain) NSString *lang; // @synthesize lang;
- (void).cxx_destruct;
- (void)stopTimer;
- (void)startTimer:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)hitPlay;
- (void)exitFolder;
- (void)viewDidLoad;
- (void)openStore:(int)arg1;
- (void)avatarsUnlocked;
- (void)setWins;
- (void)addMenu:(id)arg1;
- (void)addMenuSettings;
- (void)addMenuStore;
- (void)showCustomize:(_Bool)arg1;
- (void)showCustomize;
- (void)removeMenu;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)update;
- (_Bool)prefersHomeIndicatorAutoHidden;
- (void)showSettings:(id)arg1;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)hideSettings;
- (_Bool)canRunGame;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)handleSingleTap:(id)arg1;
- (void)backTap:(_Bool)arg1;
- (void)backTap;
- (void)toMenu:(id)arg1;
- (void)toSubmenu;
- (void)toSelector;
- (void)resetSelected;
- (void)backTap2;
- (void)backTapGesture:(id)arg1;
- (void)closeAlert:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)displayClassInfo:(Class)arg1;
- (void)viewWillLayoutSubviews;
- (void)lay;
- (void)viewDidLayoutSubviews;
- (id)initWithMain:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

