//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GAStore : NSObject
{
    struct sqlite3 *_database;
    _Bool _dbReady;
    _Bool _tableReady;
    NSString *_dbPath;
    long long _maxDbSizeBytesBeforeTrim;
    long long _maxDbSizeBytes;
}

+ (_Bool)isDbTooLargeForEvents;
+ (long long)getDbSize;
+ (void)executeQueryWithSql:(id)arg1 andParameters:(id)arg2 andCallback:(CDUnknownBlockType)arg3;
+ (void)executeQueryWithSql:(id)arg1 andCallback:(CDUnknownBlockType)arg2;
+ (id)executeQuerySyncWithSql:(id)arg1 andParameters:(id)arg2 andUseTransaction:(_Bool)arg3;
+ (id)executeQuerySyncWithSql:(id)arg1 andParameters:(id)arg2;
+ (id)executeQuerySyncWithSql:(id)arg1;
+ (void)clearStoredProgressionTriesForProgressionId:(id)arg1;
+ (void)persistProgressionTries:(id)arg1 forProgressionId:(id)arg2;
+ (void)setUserDefaultsStateWithKey:(id)arg1 andValue:(id)arg2;
+ (void)setDbStateWithKey:(id)arg1 andValue:(id)arg2;
+ (void)persistStateCachedConfigWithValue:(id)arg1;
+ (void)persistStateTransactionNumWithValue:(id)arg1;
+ (void)persistStateSessionNumWithValue:(id)arg1;
+ (void)persistStateBirthYearWithValue:(id)arg1;
+ (void)persistStateFacebookIdWithValue:(id)arg1;
+ (void)persistStateGenderWithValue:(id)arg1;
+ (void)persistStateDimension03WithValue:(id)arg1;
+ (void)persistStateDimension02WithValue:(id)arg1;
+ (void)persistStateDimension01WithValue:(id)arg1;
+ (void)persistStateRandomUserId:(id)arg1;
+ (void)setSharedInstance:(id)arg1;
+ (id)sharedInstance;
@property(nonatomic) _Bool tableReady; // @synthesize tableReady=_tableReady;
@property(nonatomic) _Bool dbReady; // @synthesize dbReady=_dbReady;
@property(nonatomic) long long maxDbSizeBytes; // @synthesize maxDbSizeBytes=_maxDbSizeBytes;
@property(nonatomic) long long maxDbSizeBytesBeforeTrim; // @synthesize maxDbSizeBytesBeforeTrim=_maxDbSizeBytesBeforeTrim;
@property(retain, nonatomic) NSString *dbPath; // @synthesize dbPath=_dbPath;
- (void).cxx_destruct;
- (_Bool)ensureDatabase:(_Bool)arg1;
- (_Bool)trimEventTable;
- (struct sqlite3 *)getDatabase;
- (id)init;

@end

