//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface GAThreading : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
}

+ (_Bool)isGAThread;
+ (void)performTaskOnMainThreadWithBlock:(CDUnknownBlockType)arg1;
+ (void)performTaskOnGAThreadWithBlock:(CDUnknownBlockType)arg1;
+ (void)setSharedInstance:(id)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (id)init;

@end

