//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MPAdView, MPNativeAd, NSDate, NSMutableArray, NSString;

@interface Global : NSObject
{
    id main;
    NSMutableArray *mains;
    MPNativeAd *nativeAd;
    NSDate *_nativeDate;
    NSString *_nativeId;
    MPAdView *_mrecAd;
    NSDate *_mrecDate;
    NSMutableArray *_purchased_transactions;
    id _transcript_request;
}

+ (id)instance;
+ (id)imageNamed:(id)arg1;
@property(nonatomic) __weak id transcript_request; // @synthesize transcript_request=_transcript_request;
@property(retain) NSMutableArray *purchased_transactions; // @synthesize purchased_transactions=_purchased_transactions;
@property(retain) NSDate *mrecDate; // @synthesize mrecDate=_mrecDate;
@property(retain) MPAdView *mrecAd; // @synthesize mrecAd=_mrecAd;
@property(retain) NSString *nativeId; // @synthesize nativeId=_nativeId;
@property(retain) NSDate *nativeDate; // @synthesize nativeDate=_nativeDate;
@property(retain) MPNativeAd *nativeAd; // @synthesize nativeAd;
@property(retain) NSMutableArray *mains; // @synthesize mains;
@property(retain) id main; // @synthesize main;
- (void).cxx_destruct;

@end

