//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class NSMutableArray, SKSpriteNode;

@interface GolfBall : SKNode
{
    _Bool ingame;
    _Bool hole;
    _Bool inside;
    int player;
    float dist;
    float rotation;
    float hole_speed;
    struct b2Body *body;
    SKSpriteNode *sprite;
    SKSpriteNode *arrow;
    SKSpriteNode *shadow;
    SKSpriteNode *round;
    struct b2Vec2 pos;
    NSMutableArray *dots;
}

@property _Bool inside; // @synthesize inside;
@property float hole_speed; // @synthesize hole_speed;
@property _Bool hole; // @synthesize hole;
@property float rotation; // @synthesize rotation;
@property(retain) NSMutableArray *dots; // @synthesize dots;
@property struct b2Vec2 pos; // @synthesize pos;
@property _Bool ingame; // @synthesize ingame;
@property(retain) SKSpriteNode *round; // @synthesize round;
@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
@property float dist; // @synthesize dist;
@property(retain) SKSpriteNode *arrow; // @synthesize arrow;
@property(retain) SKSpriteNode *sprite; // @synthesize sprite;
@property int player; // @synthesize player;
@property struct b2Body *body; // @synthesize body;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setPuck:(int)arg1;
- (void)blink;
- (void)unblink;
- (void)setDir:(float)arg1 dist:(float)arg2;
- (void)showDots;
- (void)hideDots;
- (id)init;

@end

