//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKSpriteNode.h"

@interface GolfSlope : SKSpriteNode
{
    float vx;
    float vy;
}

@property float vy; // @synthesize vy;
@property float vx; // @synthesize vx;
- (id)initWithImageNamed:(id)arg1;

@end

