//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SKScene, UIImageView, UILabel, WKWebView;

@interface HelpScreen : UIView
{
    UILabel *soon;
    WKWebView *web;
    UIImageView *close;
    UIView *top;
    UILabel *label;
    SKScene *sscene;
}

@property(nonatomic) __weak SKScene *sscene; // @synthesize sscene;
@property(retain) UILabel *label; // @synthesize label;
@property(retain) UIView *top; // @synthesize top;
@property(retain) UIImageView *close; // @synthesize close;
@property(retain) WKWebView *web; // @synthesize web;
- (void).cxx_destruct;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 scene:(id)arg2;
- (void)closeTapGesture:(id)arg1;

@end

