//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameScene.h"

@class ActionButton, GoalNode, KnockPenguin, NSDate, NSMutableArray, NSMutableString, NSString, PoolSkipButton, SKAudioNode, SKLabelNode, SKNode, SKShapeNode, SKSpriteNode, ShufflePuck, TipNode;

@interface KnockScene : GameScene
{
    _Bool created;
    NSString *mode;
    NSMutableArray *particles;
    SKSpriteNode *board;
    SKSpriteNode *board2;
    SKNode *table;
    struct b2World *world;
    ShufflePuck *puck;
    SKNode *selected;
    struct CGPoint last_pos;
    struct CGPoint puck_pos;
    float speed;
    float board_size;
    float board_size_h;
    PoolSkipButton *skip_button;
    SKSpriteNode *arrow;
    int state;
    int player;
    NSString *player_id1;
    NSString *player_id2;
    int score1;
    int score2;
    _Bool shot;
    NSMutableString *replay_send;
    NSMutableString *pre_send;
    NSMutableArray *replay;
    SKLabelNode *score1_label;
    SKLabelNode *score2_label;
    NSMutableArray *nuke;
    ActionButton *actionButton;
    TipNode *tip;
    float left;
    float right;
    SKSpriteNode *marker1;
    SKSpriteNode *marker2;
    _Bool shown;
    GoalNode *goal;
    SKSpriteNode *bg_node;
    KnockPenguin *tip_penguin;
    SKAudioNode *drag_sound;
    shared_ptr_352a3a4b drag_sound2;
    int melt;
    int win;
    NSDate *last_hit;
    struct KnockContactListener *listener;
    SKShapeNode *_spinnyNode;
    SKLabelNode *_label;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)resize;
- (void)sendMessage;
- (id)exportBoard:(_Bool)arg1;
- (id)exportBoard;
- (void)blink;
- (void)setBoard:(id)arg1;
- (void)playReplay;
- (void)new_round;
- (void)skip;
- (void)Skip;
- (id)parseReplay:(id)arg1;
- (void)testWin;
- (void)receiveMessage:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)ShootShoot;
- (void)Shoot;
- (void)savePlaceBack:(id)arg1 what:(id)arg2;
- (void)placeBack:(id)arg1;
- (id)generatePreview;
- (id)getPreview;
- (void)ball_hit:(float)arg1;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)closeGoal;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (struct CGPoint)Slerp:(struct CGPoint)arg1 pos2:(struct CGPoint)arg2 ratio:(float)arg3;
- (void)unload;
- (void)update:(double)arg1;
- (id)create;
- (void)ActionShoot;
- (void)Splash:(id)arg1;
- (void)createSceneContents;
- (void)didMoveToView:(id)arg1;
- (id)initWithMain:(id)arg1 msg:(id)arg2;

@end

