//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtobufMessage.h"

@class NSMutableArray, NSString;

@interface LoadIndexRangeArgs : NSObject <ProtobufMessage>
{
    int cachedSize;
    int cachedSizeId;
    int limit;
    NSString *table;
    NSString *index;
    NSMutableArray *startIndexValue;
    NSMutableArray *stopIndexValue;
}

+ (id)loadIndexRangeArgsWithTable:(id)arg1 index:(id)arg2 startIndexValue:(id)arg3 stopIndexValue:(id)arg4 limit:(int)arg5;
@property int limit; // @synthesize limit;
@property(retain) NSMutableArray *stopIndexValue; // @synthesize stopIndexValue;
@property(retain) NSMutableArray *startIndexValue; // @synthesize startIndexValue;
@property(retain) NSString *index; // @synthesize index;
@property(retain) NSString *table; // @synthesize table;
- (int)sizeWithCacheId:(int)arg1;
- (void)deserializeFromReader:(id)arg1;
- (void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2;
- (id)initWithTable:(id)arg1 index:(id)arg2 startIndexValue:(id)arg3 stopIndexValue:(id)arg4 limit:(int)arg5;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

