//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface Localize : NSObject
{
    NSString *lang;
    NSDictionary *dict;
    NSDictionary *dict2;
}

+ (id)instance;
- (void).cxx_destruct;
- (id)getStringForId:(id)arg1;
- (id)init;
- (id)getLang;

@end

