//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class MancalaSpot, SKSpriteNode;

@interface MancalaPiece : SKNode
{
    _Bool instant;
    _Bool up;
    int player;
    float vy;
    int num;
    SKSpriteNode *sprite;
    SKSpriteNode *shadow;
    SKSpriteNode *shade;
    MancalaSpot *spot;
    struct CGPoint pos;
}

@property _Bool up; // @synthesize up;
@property(retain) MancalaSpot *spot; // @synthesize spot;
@property int num; // @synthesize num;
@property(retain) SKSpriteNode *shade; // @synthesize shade;
@property _Bool instant; // @synthesize instant;
@property float vy; // @synthesize vy;
@property struct CGPoint pos; // @synthesize pos;
@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
@property(retain) SKSpriteNode *sprite; // @synthesize sprite;
@property int player; // @synthesize player;
- (void).cxx_destruct;
- (void)setPiece:(int)arg1 style:(int)arg2;
- (void)setPiece:(int)arg1;
- (void)blink;
- (void)blinkWin;
- (void)unblink;
- (id)init;

@end

