//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKLabelNode, SKSpriteNode;

@interface MancalaTip : SKNode
{
    SKSpriteNode *shadow;
    SKNode *container;
    SKSpriteNode *answer_bg;
    SKSpriteNode *answer_shadow;
    SKSpriteNode *bg;
    SKLabelNode *answer;
}

@property(retain) SKLabelNode *answer; // @synthesize answer;
@property(retain) SKSpriteNode *bg; // @synthesize bg;
- (void).cxx_destruct;
- (void)setText:(id)arg1;
- (void)setWhite;
- (void)setGreen;
- (void)setRepeat;
- (id)init;

@end

