//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSMutableArray, PIOMessage;

@interface MessageSerializer : NSObject
{
    NSData *_savedBytes;
    PIOMessage *_message;
    int _partsInMessage;
    NSMutableArray *_parsedMessages;
}

+ (double)doubleFromBytes:(const char *)arg1 position:(unsigned long long)arg2 length:(unsigned long long)arg3;
+ (float)floatFromBytes:(const char *)arg1 position:(unsigned long long)arg2 length:(unsigned long long)arg3;
+ (unsigned long long)ulongFromBytes:(const char *)arg1 position:(unsigned long long)arg2 length:(unsigned long long)arg3;
+ (long long)longFromBytes:(const char *)arg1 position:(unsigned long long)arg2 length:(unsigned long long)arg3;
+ (unsigned int)uintFromBytes:(const char *)arg1 position:(unsigned long long)arg2 length:(unsigned long long)arg3;
+ (int)intFromBytes:(const char *)arg1 position:(unsigned long long)arg2 length:(unsigned long long)arg3;
+ (id)stringFromBytes:(const char *)arg1 position:(unsigned long long)arg2 length:(unsigned long long)arg3;
+ (id)dataFromDouble:(double)arg1;
+ (id)dataFromFloat:(float)arg1;
+ (id)dataFromULong:(unsigned long long)arg1;
+ (id)dataFromLong:(long long)arg1;
+ (id)dataFromUInt:(unsigned int)arg1;
+ (id)dataFromInt:(int)arg1;
+ (id)dataFromString:(id)arg1;
- (void)deserializeBytes:(const char *)arg1 start:(unsigned long long)arg2 count:(unsigned long long)arg3;
- (unsigned long long)serializeMessage:(id)arg1 target:(id)arg2;
- (id)serializeMessage:(id)arg1;
- (id)nextMessage;
- (void)dealloc;
- (id)init;

@end

