//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSMessagesAppViewController.h"

#import "MPNativeAdDelegate.h"
#import "SKPaymentTransactionObserver.h"
#import "SKProductsRequestDelegate.h"
#import "SKRequestDelegate.h"

@class MSConversation, MSMessage, NSArray, NSMutableDictionary, NSString, NSTimer, NSUserDefaults, SKProductsRequest, SKReceiptRefreshRequest, UIView, UIViewController;

@interface MessagesViewController : MSMessagesAppViewController <SKProductsRequestDelegate, SKPaymentTransactionObserver, MPNativeAdDelegate, SKRequestDelegate>
{
    UIViewController *transcriptView;
    UIView *view2;
    _Bool started;
    _Bool sending;
    MSMessage *sending_msg;
    _Bool cloud_synced;
    SKProductsRequest *product_request;
    NSArray *products;
    _Bool trans_added;
    NSTimer *timer;
    _Bool initialized;
    SKReceiptRefreshRequest *rr;
    _Bool send_progress;
    _Bool pressed;
    _Bool _death;
    _Bool _tapped;
    _Bool _instant_send;
    _Bool _transitioning;
    int buying_state;
    MSConversation *convo;
    NSUserDefaults *prefs;
    NSArray *games;
    UIViewController *gameVC;
    NSMutableDictionary *once_dictionary;
    NSMutableDictionary *game_configs;
    NSMutableDictionary *_store_prices;
    NSArray *_productIdentifiers;
    NSString *_buying_item;
    NSString *_app_lang;
    NSMutableDictionary *_people_dictionary;
}

+ (_Bool)mp_supportsOrientationMask:(unsigned long long)arg1;
+ (_Bool)mp_doesOrientation:(long long)arg1 matchOrientationMask:(unsigned long long)arg2;
+ (_Bool)openURL:(id)arg1;
+ (long long)applicationState;
+ (long long)orientation;
+ (id)window;
+ (id)contr;
+ (id)test;
@property _Bool transitioning; // @synthesize transitioning=_transitioning;
@property(retain) NSMutableDictionary *people_dictionary; // @synthesize people_dictionary=_people_dictionary;
@property(retain) NSString *app_lang; // @synthesize app_lang=_app_lang;
@property _Bool instant_send; // @synthesize instant_send=_instant_send;
@property _Bool tapped; // @synthesize tapped=_tapped;
@property _Bool death; // @synthesize death=_death;
@property(retain) NSString *buying_item; // @synthesize buying_item=_buying_item;
@property(retain) NSArray *productIdentifiers; // @synthesize productIdentifiers=_productIdentifiers;
@property(retain) NSMutableDictionary *store_prices; // @synthesize store_prices=_store_prices;
@property(retain) NSMutableDictionary *game_configs; // @synthesize game_configs;
@property(retain) NSMutableDictionary *once_dictionary; // @synthesize once_dictionary;
@property _Bool pressed; // @synthesize pressed;
@property(retain) UIViewController *gameVC; // @synthesize gameVC;
@property(retain) NSArray *games; // @synthesize games;
@property int buying_state; // @synthesize buying_state;
@property(retain) NSUserDefaults *prefs; // @synthesize prefs;
@property(retain) MSConversation *convo; // @synthesize convo;
@property _Bool send_progress; // @synthesize send_progress;
- (void).cxx_destruct;
- (void)refreshScreen;
- (void)alert:(id)arg1 msg:(id)arg2 button:(id)arg3;
- (void)alert:(id)arg1 msg:(id)arg2;
- (struct CGRect)screenRect;
- (void)receivedSMS:(id)arg1 from:(id)arg2;
- (void)hideSMS;
- (void)focusSMS;
- (void)initSMS;
- (void)showSMS;
- (void)openStore:(int)arg1;
- (void)didTransitionToPresentationStyle:(unsigned long long)arg1;
- (void)willSelectMessage:(id)arg1 conversation:(id)arg2;
- (void)didSelectMessage:(id)arg1 conversation:(id)arg2;
- (void)menuExpand;
- (void)menuMinimize;
- (void)willTransitionToPresentationStyle:(unsigned long long)arg1;
- (_Bool)iOS11;
- (void)showCustomize:(_Bool)arg1;
- (void)showCustomize;
- (_Bool)prefersHomeIndicatorAutoHidden;
- (void)didCancelSendingMessage:(id)arg1 conversation:(id)arg2;
- (void)didStartSendingMessage:(id)arg1 conversation:(id)arg2;
- (_Bool)isTranscript;
- (void)didReceiveMessage:(id)arg1 conversation:(id)arg2;
- (id)extractMessage:(id)arg1;
- (void)willResignActiveWithConversation:(id)arg1;
- (void)didResignActiveWithConversation:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)requestStart:(id)arg1;
- (void)requestStart;
- (id)genHuntLetter;
- (id)getHunt:(int)arg1;
- (id)genRandStringLength:(int)arg1;
- (id)playSound:(id)arg1 volume:(float)arg2;
- (id)sendMessage:(id)arg1 image:(id)arg2 caption:(id)arg3 subcaption:(id)arg4 dismiss:(_Bool)arg5 start:(_Bool)arg6 transcript:(id)arg7 instant:(_Bool)arg8;
- (id)sendMessage:(id)arg1 image:(id)arg2 caption:(id)arg3 subcaption:(id)arg4 dismiss:(_Bool)arg5 start:(_Bool)arg6 transcript:(id)arg7;
- (id)sendMessage:(id)arg1 image:(id)arg2 caption:(id)arg3 subcaption:(id)arg4 dismiss:(_Bool)arg5 start:(_Bool)arg6;
- (id)sendMessage:(id)arg1 image:(id)arg2 caption:(id)arg3 subcaption:(id)arg4 dismiss:(_Bool)arg5;
- (id)sendMessage:(id)arg1 image:(id)arg2 caption:(id)arg3 subcaption:(id)arg4;
- (void)resendMessage:(id)arg1;
- (id)fullPlayerId:(id)arg1;
- (id)fullPlayerId;
- (_Bool)isMine:(id)arg1;
- (_Bool)isMineString:(id)arg1;
- (_Bool)isMineString:(id)arg1 message:(id)arg2;
- (int)getPlayer:(id)arg1;
- (void)displayGame:(id)arg1;
- (void)diplayGameSelector;
- (void)displaySend;
- (void)lay;
- (void)viewWillLayoutSubviews;
- (void)viewDidLayoutSubviews;
- (void)changeViewWithConversation:(id)arg1 presentationStyle:(unsigned long long)arg2;
- (void)reloadGame;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)updateFromiCloud:(id)arg1;
- (int)PAU:(id)arg1;
- (void)hasCloud;
- (void)hasCloudNew;
- (void)updateiCloud;
- (id)decryptStringNew:(id)arg1;
- (id)decryptString:(id)arg1;
- (id)encyptStringNew:(id)arg1;
- (id)encyptString:(id)arg1;
- (void)removeViews;
- (void)removeOlderFiles;
- (id)loadSave:(id)arg1 force:(_Bool)arg2;
- (id)loadSave:(id)arg1;
- (void)buyAvatars;
- (void)removeImages;
- (void)removeOld;
- (_Bool)saveSave:(id)arg1 what:(id)arg2 force:(_Bool)arg3;
- (_Bool)saveSave:(id)arg1 what:(id)arg2;
- (_Bool)saveExists:(id)arg1;
- (_Bool)doOnce:(id)arg1 save:(_Bool)arg2;
- (void)savePerson:(id)arg1 dict:(id)arg2;
- (void)loadPeople;
- (int)personVersion:(id)arg1;
- (id)personInfo:(id)arg1;
- (_Bool)isVersion:(id)arg1 higherThan:(id)arg2;
- (void)analyzeMessage:(id)arg1;
- (_Bool)doOnce:(id)arg1;
- (void)trackOnce:(id)arg1;
- (void)track:(id)arg1;
- (id)applicationDirectory;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (void)processTransaction:(id)arg1;
- (void)paymentQueue:(id)arg1 restoreCompletedTransactionsFailedWithError:(id)arg2;
- (void)paymentQueue:(id)arg1 removedTransactions:(id)arg2;
- (void)buy:(id)arg1;
- (void)storeObserver;
- (void)restoreAvatars;
- (void)getPrices;
- (void)unfadeAd;
- (void)fadeAd;
- (void)hideAd;
- (void)showAd;
- (void)readyForAd;
- (void)showAd2;
- (void)updatePrefs;
- (_Bool)consumableConsume:(id)arg1 ammount:(int)arg2;
- (void)consumableAdd:(id)arg1 ammount:(int)arg2;
- (int)consumableGet:(id)arg1;
- (void)open:(id)arg1;
- (void)didBecomeActiveWithConversation:(id)arg1;
- (void)configureGames;
- (void)loadConfig;
- (void)pauseScene3d;
- (void)adViewDidLoadAd:(id)arg1;
- (void)initialize;
- (void)viewDidLoad;
- (void)update;
- (struct CGSize)contentSizeThatFits:(struct CGSize)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

