//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface MoreMenuButton : UIButton
{
    SEL _selector;
    id _target;
}

@property(retain) id target; // @synthesize target=_target;
@property SEL selector; // @synthesize selector=_selector;
- (void).cxx_destruct;

@end

