//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ButtonNode.h"

@class SKSpriteNode;

@interface MoreButton : ButtonNode
{
    _Bool iap;
    SKSpriteNode *shadow;
    SKSpriteNode *ad;
}

@property(retain) SKSpriteNode *ad; // @synthesize ad;
@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
- (void).cxx_destruct;
- (void)black;
- (void)more;
- (void)dark;
- (id)init;
- (void)showAd;
- (void)hideAd;

@end

