//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameScene.h"

@class ActionButton, NSMutableArray, NSMutableString, NSString, PaintDude, PaintGun, PaintHp, PaintTire, PoolSkipButton, SKLabelNode, SKNode, SKShapeNode, SKSpriteNode, ShufflePuck, TanksTank, TanksWind, TipNode;

@interface PaintScene : GameScene
{
    float high;
    double last_time;
    float wind_speed;
    SKSpriteNode *cloud1;
    SKSpriteNode *cloud2;
    SKSpriteNode *cloud3;
    struct TanksContactListener *listener;
    NSMutableArray *particles;
    SKNode *ground;
    SKSpriteNode *moon;
    SKSpriteNode *groundback;
    SKSpriteNode *ground1;
    SKSpriteNode *ground2;
    SKSpriteNode *ground3;
    SKSpriteNode *gb;
    SKSpriteNode *ground1_bot;
    SKSpriteNode *ground2_bot;
    SKSpriteNode *ground3_bot;
    SKSpriteNode *bg_node;
    SKSpriteNode *tower_sprite;
    SKNode *power_bar;
    SKSpriteNode *power_handle;
    SKLabelNode *power_label;
    TanksTank *tank1;
    TanksTank *tank2;
    int style1;
    int style2;
    PaintHp *hp1;
    PaintHp *hp2;
    TanksWind *wind;
    ActionButton *actionButton;
    SKSpriteNode *board;
    SKNode *table;
    struct b2World *world;
    ShufflePuck *puck;
    SKNode *selected;
    struct CGPoint last_pos;
    struct CGPoint puck_pos;
    float speed;
    float board_size;
    float board_size_h;
    PoolSkipButton *skip_button;
    int state;
    int player;
    NSString *player_id1;
    NSString *player_id2;
    int score1;
    int score2;
    _Bool shot;
    NSMutableString *replay_send;
    NSMutableString *pre_send;
    NSMutableArray *replay;
    SKLabelNode *score1_label;
    SKLabelNode *score2_label;
    SKNode *tires1;
    SKNode *tires2;
    PaintTire *enemy;
    PaintTire *target2;
    PaintTire *target;
    PaintDude *dude;
    SKSpriteNode *dude_shadow;
    SKSpriteNode *flash;
    PaintGun *gun;
    TipNode *tip;
    SKNode *effect;
    SKShapeNode *_spinnyNode;
    SKLabelNode *_label;
    NSMutableArray *nuke;
}

@property(retain) NSMutableArray *nuke; // @synthesize nuke;
- (void).cxx_destruct;
- (void)unload;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)resize;
- (void)sendMessage;
- (id)exportBoard:(_Bool)arg1;
- (id)exportBoard;
- (void)playReplay;
- (void)new_round;
- (void)SetWind:(float)arg1;
- (void)skip;
- (void)Skip;
- (id)parseReplay:(id)arg1;
- (void)receiveMessage:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (void)grass;
- (void)swing;
- (void)reset;
- (void)hit_him;
- (void)hit_me;
- (void)end_move;
- (void)check;
- (void)heShoot;
- (id)dk:(id)arg1 strength:(double)arg2;
- (void)meShoot;
- (void)showEnemy;
- (void)fpsView;
- (id)hex:(id)arg1;
- (void)anim;
- (void)anim2;
- (void)shoot;
- (struct CGPoint)Slerp:(struct CGPoint)arg1 pos2:(struct CGPoint)arg2 ratio:(float)arg3;
- (void)update:(double)arg1;
- (_Bool)checkWin;
- (_Bool)showWin;
- (void)ActionShoot;
- (void)PlayShoot;
- (void)Shoot:(float)arg1 player:(int)arg2;
- (void)savePlaceBack:(id)arg1 what:(id)arg2;
- (void)placeBack:(id)arg1;
- (id)generatePreview;
- (void)shakeCamera:(id)arg1 duration:(float)arg2 amp:(float)arg3;
- (id)create;
- (struct b2FixtureDef *)makeFixture2:(struct b2PolygonShape)arg1;
- (struct b2FixtureDef *)makeFixture:(struct b2EdgeShape)arg1;
- (void)setBoard:(id)arg1;
- (void)hideUI;
- (void)setTarget:(id)arg1;
- (void)setMoves;
- (void)createSceneContents;
- (void)didMoveToView:(id)arg1;
- (id)initWithMain:(id)arg1 msg:(id)arg2;

@end

