//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKSpriteNode;

@interface PaintGun : SKNode
{
    SKSpriteNode *node;
}

@property(retain) SKSpriteNode *node; // @synthesize node;
- (void).cxx_destruct;
- (id)init;

@end

