//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKSpriteNode;

@interface PaintHp : SKNode
{
    int hp;
    SKSpriteNode *sprite;
}

@property(retain) SKSpriteNode *sprite; // @synthesize sprite;
@property int hp; // @synthesize hp;
- (void).cxx_destruct;
- (void)setHP:(int)arg1;
- (void)blue;
- (void)red;
- (id)init;

@end

