//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKSpriteNode;

@interface PaintTire : SKNode
{
    SKSpriteNode *grass;
    SKSpriteNode *shadow;
    int type;
    int num;
    int dir;
    int style;
    int player;
    SKSpriteNode *target;
    SKSpriteNode *move;
    SKSpriteNode *enemy;
}

@property int player; // @synthesize player;
@property int style; // @synthesize style;
@property int dir; // @synthesize dir;
@property(retain) SKSpriteNode *enemy; // @synthesize enemy;
@property int num; // @synthesize num;
@property(retain) SKSpriteNode *move; // @synthesize move;
@property(retain) SKSpriteNode *target; // @synthesize target;
- (void).cxx_destruct;
- (void)hit;
- (void)shoot;
- (void)showEnemy:(int)arg1;
- (void)reset;
- (id)init:(int)arg1;

@end

