//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface PathFinder : NSObject
{
    int finX;
    int finY;
    NSMutableArray *level;
    NSMutableDictionary *openList;
    NSMutableDictionary *closedList;
    NSMutableArray *path;
}

+ (id)go:(int)arg1 yIni:(int)arg2 xFin:(int)arg3 yFin:(int)arg4 lvlData:(id)arg5;
@property(retain) NSMutableArray *path; // @synthesize path;
- (void).cxx_destruct;
- (void)RetracePath:(id)arg1;
- (void)SearchLevel;
- (id)initWith:(int)arg1 yIni:(int)arg2 xFin:(int)arg3 yFin:(int)arg4 lvlData:(id)arg5;

@end

