//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PathNode : NSObject
{
    int x;
    int y;
    int h;
    int g;
    PathNode *parentNode;
}

@property(retain) PathNode *parentNode; // @synthesize parentNode;
@property int g; // @synthesize g;
@property int h; // @synthesize h;
@property int y; // @synthesize y;
@property int x; // @synthesize x;
- (void).cxx_destruct;
- (id)initWith:(int)arg1 yPos:(int)arg2 gVal:(int)arg3 hVal:(int)arg4 link:(id)arg5;

@end

