//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtobufMessage.h"

@class NSString;

@interface PayVaultReadHistoryArgs : NSObject <ProtobufMessage>
{
    int cachedSize;
    int cachedSizeId;
    unsigned int page;
    unsigned int pageSize;
    NSString *targetUserId;
}

+ (id)payVaultReadHistoryArgsWithPage:(unsigned int)arg1 pageSize:(unsigned int)arg2 targetUserId:(id)arg3;
@property(retain) NSString *targetUserId; // @synthesize targetUserId;
@property unsigned int pageSize; // @synthesize pageSize;
@property unsigned int page; // @synthesize page;
- (int)sizeWithCacheId:(int)arg1;
- (void)deserializeFromReader:(id)arg1;
- (void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2;
- (id)initWithPage:(unsigned int)arg1 pageSize:(unsigned int)arg2 targetUserId:(id)arg3;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

