//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtobufMessage.h"

@class NSMutableArray, NSString;

@interface PayVaultHistoryEntry : NSObject <ProtobufMessage>
{
    int cachedSize;
    int cachedSizeId;
    int amount;
    NSString *type;
    long long timestamp;
    NSMutableArray *itemKeys;
    NSString *reason;
    NSString *providerTransactionId;
    NSString *providerPrice;
}

+ (id)payVaultHistoryEntryWithAmount:(int)arg1 type:(id)arg2 timestamp:(long long)arg3 itemKeys:(id)arg4 reason:(id)arg5 providerTransactionId:(id)arg6 providerPrice:(id)arg7;
@property(retain) NSString *providerPrice; // @synthesize providerPrice;
@property(retain) NSString *providerTransactionId; // @synthesize providerTransactionId;
@property(retain) NSString *reason; // @synthesize reason;
@property(retain) NSMutableArray *itemKeys; // @synthesize itemKeys;
@property long long timestamp; // @synthesize timestamp;
@property(retain) NSString *type; // @synthesize type;
@property int amount; // @synthesize amount;
- (int)sizeWithCacheId:(int)arg1;
- (void)deserializeFromReader:(id)arg1;
- (void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2;
- (id)initWithAmount:(int)arg1 type:(id)arg2 timestamp:(long long)arg3 itemKeys:(id)arg4 reason:(id)arg5 providerTransactionId:(id)arg6 providerPrice:(id)arg7;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

