//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PSWebSocketDelegate.h"
#import "PeerGateDelegate.h"

@class NSData, NSDate, NSString, NSTimer, PSWebSocket;

@interface Peer : NSObject <PeerGateDelegate, PSWebSocketDelegate>
{
    unsigned char _players;
    _Bool _connected;
    _Bool _server;
    _Bool _authorized;
    _Bool _reconnecting;
    unsigned short _pid;
    unsigned short _version;
    int _reconnect_max;
    int _reconnect_count;
    int _reconnect_timeout;
    int _port;
    int _peer_num;
    int _events;
    id <PeerDelegate> _delegate;
    NSString *_player_id;
    NSString *_game_id;
    NSString *_game;
    NSString *_game_name;
    NSString *_host;
    PSWebSocket *_socket;
    NSTimer *_timer;
    NSDate *_last_sent;
    NSDate *_last_received;
    NSDate *_ping_sent;
    NSData *_data;
}

@property(retain) NSData *data; // @synthesize data=_data;
@property(retain) NSDate *ping_sent; // @synthesize ping_sent=_ping_sent;
@property(retain) NSDate *last_received; // @synthesize last_received=_last_received;
@property(retain) NSDate *last_sent; // @synthesize last_sent=_last_sent;
@property __weak NSTimer *timer; // @synthesize timer=_timer;
@property int events; // @synthesize events=_events;
@property _Bool reconnecting; // @synthesize reconnecting=_reconnecting;
@property _Bool authorized; // @synthesize authorized=_authorized;
@property _Bool server; // @synthesize server=_server;
@property _Bool connected; // @synthesize connected=_connected;
@property(retain) PSWebSocket *socket; // @synthesize socket=_socket;
@property unsigned char players; // @synthesize players=_players;
@property int peer_num; // @synthesize peer_num=_peer_num;
@property int port; // @synthesize port=_port;
@property(retain) NSString *host; // @synthesize host=_host;
@property(retain) NSString *game_name; // @synthesize game_name=_game_name;
@property(retain) NSString *game; // @synthesize game=_game;
@property unsigned short version; // @synthesize version=_version;
@property(retain) NSString *game_id; // @synthesize game_id=_game_id;
@property(retain) NSString *player_id; // @synthesize player_id=_player_id;
@property unsigned short pid; // @synthesize pid=_pid;
@property int reconnect_timeout; // @synthesize reconnect_timeout=_reconnect_timeout;
@property int reconnect_count; // @synthesize reconnect_count=_reconnect_count;
@property int reconnect_max; // @synthesize reconnect_max=_reconnect_max;
@property(nonatomic) __weak id <PeerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)send:(id)arg1 encrypted:(_Bool)arg2;
- (void)send:(id)arg1;
- (void)sendMessage:(id)arg1;
- (void)webSocket:(id)arg1 didCloseWithCode:(long long)arg2 reason:(id)arg3 wasClean:(_Bool)arg4;
- (void)webSocket:(id)arg1 didFailWithError:(id)arg2;
- (void)webSocket:(id)arg1 didReceiveMessage:(id)arg2;
- (void)webSocketDidOpen:(id)arg1;
- (void)didDisconnect;
- (void)didConnect;
- (void)connect:(id)arg1 port:(int)arg2 game:(id)arg3;
- (void)connect:(id)arg1 port:(int)arg2;
- (void)disconnect;
- (void)connect:(id)arg1 player_id:(id)arg2 game_name:(id)arg3 players:(unsigned char)arg4;
- (void)connect:(id)arg1 player_id:(id)arg2 game_name:(id)arg3 players:(unsigned char)arg4 data:(id)arg5;
- (void)internal_connect:(id)arg1 player_id:(id)arg2 game_name:(id)arg3 players:(unsigned char)arg4 data:(id)arg5;
- (void)reconnect:(int)arg1;
- (void)PeerGateConnected:(id)arg1 data:(id)arg2;
- (void)PeerGateReconnect:(id)arg1 data:(id)arg2;
- (void)PeerGateError:(id)arg1 error:(id)arg2;
- (void)sendPing;
- (void)update;
- (void)dealloc;
- (void)invalidate;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

