//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData;

@interface PeerMessage : NSObject
{
    unsigned char _subject;
    int _position;
    NSMutableData *_data;
}

@property int position; // @synthesize position=_position;
@property(retain) NSMutableData *data; // @synthesize data=_data;
@property unsigned char subject; // @synthesize subject=_subject;
- (void).cxx_destruct;
- (void)writeString:(id)arg1;
- (void)writeData:(id)arg1;
- (void)writeFloat:(float)arg1;
- (void)writeLong:(long long)arg1;
- (void)writeUInt:(unsigned int)arg1;
- (void)writeInt:(int)arg1;
- (void)writeUShort:(unsigned short)arg1;
- (void)writeShort:(short)arg1;
- (void)writeByte:(unsigned char)arg1;
- (unsigned char)readByte;
- (id)readString;
- (float)readFloat;
- (long long)readLong;
- (unsigned int)readUInt;
- (int)readInt;
- (short)readShort;
- (unsigned short)readUShort;
- (id)initWithSubject:(unsigned char)arg1;
- (id)initWithData:(id)arg1;
- (id)init;

@end

