//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString;

@protocol PeerGateDelegate <NSObject>
- (void)PeerGateError:(id)arg1 error:(NSError *)arg2;
- (void)PeerGateReconnect:(id)arg1 data:(NSString *)arg2;
- (void)PeerGateConnected:(id)arg1 data:(NSString *)arg2;
@end

