//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@protocol PeerDelegate <NSObject>
- (void)PeerFailed:(id)arg1 code:(int)arg2;
- (void)PeerDisconnected:(id)arg1;
- (void)PeerMessage:(id)arg1 data:(NSData *)arg2;
- (void)PeerGateConnected:(id)arg1;
- (void)PeerConnected:(id)arg1;
@end

