//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PeerGate : NSObject
{
    id <PeerGateDelegate> _delegate;
}

@property(nonatomic) __weak id <PeerGateDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)connect:(id)arg1 player_id:(id)arg2 game_name:(id)arg3 players:(unsigned char)arg4;

@end

