//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData, PlayerIOChannel;

@interface PlayerIOChannelAsyncRequestDelegate : NSObject
{
    int methodId;
    PlayerIOChannel *channel;
    NSMutableData *receivedData;
    id <ProtobufMessage> output;
    CDUnknownBlockType successBlock;
    CDUnknownBlockType errorBlock;
}

- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)dealloc;
- (id)initWithChannel:(id)arg1 methodId:(int)arg2 output:(id)arg3 successBlock:(CDUnknownBlockType)arg4 errorBlock:(CDUnknownBlockType)arg5;
- (id)init;

@end

