//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PlayerIO : NSObject
{
}

+ (void)logout;
+ (void)authSuccessWithClient:(id)arg1 channel:(id)arg2 dialogs:(id)arg3 isInstalledByYahoo:(_Bool)arg4 successBlock:(CDUnknownBlockType)arg5;
+ (void)authenticateWithGameId:(id)arg1 connectionId:(id)arg2 authenticationArguments:(id)arg3 playerInsightSegments:(id)arg4 successDataBlock:(CDUnknownBlockType)arg5 errorBlock:(CDUnknownBlockType)arg6;
+ (void)authenticateWithGameId:(id)arg1 connectionId:(id)arg2 authenticationArguments:(id)arg3 playerInsightSegments:(id)arg4 successBlock:(CDUnknownBlockType)arg5 errorBlock:(CDUnknownBlockType)arg6;
+ (void)authenticateWithGameId:(id)arg1 connectionId:(id)arg2 authenticationArguments:(id)arg3 playerInsightSegments:(id)arg4 successBlock:(CDUnknownBlockType)arg5;
+ (id)getClientInfo;
+ (id)getClientAPI;
+ (id)calcAuth256WithUserId:(id)arg1 sharedSecret:(id)arg2;
+ (id)calcAuthWithUserId:(id)arg1 sharedSecret:(id)arg2;
+ (id)gameFSWithGameId:(id)arg1;
+ (void)useSecureApiRequest:(_Bool)arg1;
+ (_Bool)useSecureApiRequest;
- (id)init;

@end

