//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKSpriteNode.h"

@interface PokerCard : SKSpriteNode
{
    _Bool secret;
    int suit;
    int rank;
    int num;
    float instant;
}

@property float instant; // @synthesize instant;
@property _Bool secret; // @synthesize secret;
@property int num; // @synthesize num;
@property int rank; // @synthesize rank;
@property int suit; // @synthesize suit;
- (void)updateTexture;
- (void)setCard:(int)arg1;
- (void)setCard:(int)arg1 rank:(int)arg2;
- (id)initWithCard:(int)arg1;
- (id)initWithCard:(int)arg1 rank:(int)arg2;
- (id)init;

@end

