//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class NSString, SKLabelNode, SKSpriteNode;

@interface PokerChat : SKNode
{
    NSString *string;
    SKSpriteNode *border;
    SKLabelNode *txt;
}

@property(retain) SKLabelNode *txt; // @synthesize txt;
@property(retain) SKSpriteNode *border; // @synthesize border;
- (void).cxx_destruct;
- (void)setBlue;
- (void)setRed;
- (void)setGreen;
- (void)setTip:(id)arg1;
- (void)setBorder:(_Bool)arg1 color:(id)arg2;
- (id)init;

@end

