//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class NSMutableArray, SKSpriteNode;

@interface PokerStack : SKNode
{
    int value;
    NSMutableArray *chips;
    SKSpriteNode *shadow;
}

@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
@property int value; // @synthesize value;
@property(retain) NSMutableArray *chips; // @synthesize chips;
- (void).cxx_destruct;
- (void)updateChips;
- (void)Jump;
- (void)setBank:(int)arg1 stack:(id)arg2;
- (void)Add:(id)arg1;
- (void)setBank:(int)arg1;
- (id)init;

@end

