//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameScene.h"

@class ActionButton, NSMutableArray, NSMutableDictionary, NSMutableString, NSString, PokerCard, PokerChat, PokerStack, SKLabelNode, SKNode, SKSpriteNode, TipNode, YouNode;

@interface PokerScene : GameScene
{
    NSString *player_id1;
    NSString *player_id2;
    SKSpriteNode *bg_node;
    SKSpriteNode *dealer_node;
    struct CGPoint touch;
    YouNode *you;
    SKNode *selected;
    int player;
    int player2;
    _Bool mine;
    int state;
    TipNode *tip;
    SKNode *board;
    int bank1;
    int bank2;
    int pot;
    SKLabelNode *pot_label;
    SKLabelNode *score1;
    SKLabelNode *score2;
    SKLabelNode *bid1_label;
    SKLabelNode *bid2_label;
    int bid1;
    int bid2;
    NSMutableArray *river;
    PokerChat *chat;
    PokerCard *card1;
    PokerCard *card2;
    PokerCard *enemy_card1;
    PokerCard *enemy_card2;
    PokerStack *stack1;
    PokerStack *stack2;
    PokerStack *bid1_stack;
    PokerStack *bid2_stack;
    PokerStack *pot_stack;
    ActionButton *fold_button;
    ActionButton *call_button;
    ActionButton *raise_button;
    ActionButton *change_button;
    float pressure;
    SKSpriteNode *pot_mid;
    SKSpriteNode *pot_right;
    SKSpriteNode *pot_left;
    int bid;
    int raise;
    int call;
    NSMutableArray *cards;
    NSMutableString *replay_send;
    NSMutableArray *replay;
    int win_state;
    int queue;
    int dealer;
    SKLabelNode *what1;
    SKLabelNode *what2;
    NSMutableDictionary *send_move;
    _Bool folded;
}

- (void).cxx_destruct;
- (id)BestCombo:(int)arg1;
- (void)resize;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (void)update:(double)arg1;
- (void)Bid:(int)arg1 player:(int)arg2;
- (void)Pot:(int)arg1;
- (void)Win:(id)arg1 player:(int)arg2;
- (void)WinAll:(int)arg1;
- (void)WinHalf;
- (void)WinAll1;
- (void)SetPot:(int)arg1;
- (void)SetPot:(int)arg1 stack:(id)arg2;
- (void)SetBank:(int)arg1 player:(int)arg2 stack:(id)arg3;
- (void)SetBank:(int)arg1 player:(int)arg2;
- (void)bidOrient;
- (void)SetBid:(int)arg1 player:(int)arg2 stack:(id)arg3;
- (void)SetBid:(int)arg1 player:(int)arg2;
- (void)PotAll;
- (void)hideChat;
- (void)Bid;
- (void)Bid2;
- (struct CGPoint)Slerp:(struct CGPoint)arg1 pos2:(struct CGPoint)arg2 ratio:(float)arg3;
- (void)setRaise:(int)arg1;
- (void)setCall:(int)arg1;
- (void)Minus;
- (void)Plus;
- (void)Raise;
- (void)Call;
- (void)Fold;
- (void)Check;
- (void)AfterAction;
- (void)ShowWinner;
- (void)showWin;
- (void)ShowCards;
- (void)NewGameStarted;
- (void)NewGameAction;
- (void)ActionWin;
- (void)ActionPotAll;
- (void)AddRiverAction;
- (void)ActionRaise;
- (void)ActionCall;
- (void)ActionBet;
- (void)ActionFold;
- (void)ActionCheck;
- (id)saveBoard;
- (void)Action;
- (void)AddCard:(int)arg1 player:(int)arg2 which:(int)arg3 instant:(_Bool)arg4;
- (void)AddCard:(int)arg1 player:(int)arg2 which:(int)arg3;
- (void)resetCardPosition:(id)arg1;
- (void)ShowCombos;
- (void)AddRiverCard:(int)arg1 instant:(_Bool)arg2;
- (void)AddRiverCard:(int)arg1;
- (int)GetCard:(int)arg1;
- (int)GetRandomCard:(id)arg1;
- (int)GetRandomCard;
- (void)savePlaceBack:(id)arg1 what:(id)arg2;
- (void)placeBack:(id)arg1;
- (id)generatePreview;
- (id)getPreview;
- (void)sendMessage;
- (id)parseReplay:(id)arg1;
- (void)setBoard:(id)arg1;
- (void)AddBlinds:(int)arg1;
- (void)addCards:(int)arg1 c2:(int)arg2 c3:(int)arg3 c4:(int)arg4;
- (void)playReplay;
- (void)playNextReplay;
- (void)receiveMessage:(id)arg1;
- (void)createSceneContents;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)didMoveToView:(id)arg1;
- (id)initWithMain:(id)arg1 msg:(id)arg2;

@end

