//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKSpriteNode;

@interface PoolBall : SKNode
{
    _Bool destroyed;
    _Bool setup;
    int type;
    float spin_power;
    int delay;
    float rotationX;
    float rotationZ;
    float rotationY;
    float spinX;
    float spinY;
    int num;
    struct b2Vec2 spin_vec;
    struct b2Vec2 hole;
    SKSpriteNode *sprite;
    SKSpriteNode *shade;
    SKSpriteNode *shadow;
    SKSpriteNode *round;
    struct b2Body *body;
    struct b2Vec2 hit_hole;
}

@property _Bool setup; // @synthesize setup;
@property struct b2Vec2 hit_hole; // @synthesize hit_hole;
@property struct b2Body *body; // @synthesize body;
@property(retain) SKSpriteNode *round; // @synthesize round;
@property _Bool destroyed; // @synthesize destroyed;
@property int num; // @synthesize num;
@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
@property(retain) SKSpriteNode *shade; // @synthesize shade;
@property(retain) SKSpriteNode *sprite; // @synthesize sprite;
@property struct b2Vec2 hole; // @synthesize hole;
@property float spinY; // @synthesize spinY;
@property float spinX; // @synthesize spinX;
@property float rotationY; // @synthesize rotationY;
@property float rotationZ; // @synthesize rotationZ;
@property float rotationX; // @synthesize rotationX;
@property int delay; // @synthesize delay;
@property struct b2Vec2 spin_vec; // @synthesize spin_vec;
@property float spin_power; // @synthesize spin_power;
@property int type; // @synthesize type;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateRotations;
- (_Bool)isSolid;
- (_Bool)isStripes;
- (_Bool)isBlack;
- (_Bool)isNine;
- (void)blink;
- (void)unblink;
- (id)initWithType:(int)arg1 num:(int)arg2;

@end

