//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKCropNode, SKSpriteNode, Sprite;

@interface PoolPower : SKNode
{
    float power;
    SKSpriteNode *cue;
    SKSpriteNode *shadow;
    SKSpriteNode *area;
    SKSpriteNode *rail;
    Sprite *rail_blue;
    SKSpriteNode *rail_mask;
    SKSpriteNode *rail_lines;
    SKCropNode *mask;
    SKSpriteNode *rail_area;
}

@property(retain) SKSpriteNode *rail_area; // @synthesize rail_area;
@property(retain) SKCropNode *mask; // @synthesize mask;
@property(retain) SKSpriteNode *rail_lines; // @synthesize rail_lines;
@property(retain) SKSpriteNode *rail_mask; // @synthesize rail_mask;
@property(retain) Sprite *rail_blue; // @synthesize rail_blue;
@property(retain) SKSpriteNode *rail; // @synthesize rail;
@property float power; // @synthesize power;
@property(retain) SKSpriteNode *area; // @synthesize area;
@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
@property(retain) SKSpriteNode *cue; // @synthesize cue;
- (void).cxx_destruct;
- (id)init;

@end

