//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class NSMutableArray;

@interface PoolBalls : SKNode
{
    NSMutableArray *balls;
}

@property(retain) NSMutableArray *balls; // @synthesize balls;
- (void).cxx_destruct;
- (id)init;

@end

