//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameScene.h"

@class NSDate, NSMutableArray, NSMutableString, NSString, PoolGlow, PoolPower, PoolSkipButton, SKAudioNode, SKCropNode, SKNode, SKShapeNode, SKSpriteNode, TipNode, YouNode;

@interface PoolScene : GameScene
{
    _Bool made_walls;
    int v2;
    int v3;
    int v4;
    int v5;
    _Bool first_shot;
    int style1;
    int style2;
    int ENEMY;
    int BULLET;
    int WALL;
    float fric;
    float fric2;
    float rad;
    float sc;
    float yt;
    float pt;
    float hole_radius;
    struct b2Vec2 center_ball;
    struct b2Vec2 table_center;
    float board_size;
    float board_size_h;
    struct PoolContactListener *listener;
    struct PoolGhostContactListener *listener2;
    SKNode *table;
    SKSpriteNode *board;
    SKSpriteNode *board_top;
    SKSpriteNode *board_black;
    SKShapeNode *canvas;
    SKSpriteNode *black;
    SKSpriteNode *cue;
    SKSpriteNode *cue_shadow;
    PoolPower *power_cue;
    SKSpriteNode *ball1;
    SKSpriteNode *ball2;
    SKSpriteNode *cue_ball;
    SKSpriteNode *cue_ball_dot;
    SKSpriteNode *move;
    struct b2World *world;
    struct b2World *ghost_world;
    struct b2PolygonShape poly;
    struct CGPoint touch;
    float direction;
    float rvel;
    float rspeed;
    float last_drag;
    float start_direction;
    struct b2Vec2 *vec2;
    _Bool move_white;
    _Bool moving;
    struct b2Body *white;
    struct b2Body *black_ball;
    struct b2Body *ghost_white;
    _Bool touchDown;
    struct b2Vec2 holes[6];
    struct b2Vec2 glow_holes[6];
    NSMutableArray *nuke;
    YouNode *you;
    SKNode *selected;
    NSMutableString *replay_send;
    NSMutableArray *replay;
    int player;
    int player2;
    NSString *player_id1;
    NSString *player_id2;
    _Bool mine;
    int state;
    TipNode *tip;
    int left;
    int right;
    int stripes;
    _Bool stripes_assigned;
    _Bool scored;
    NSMutableArray *glows;
    PoolGlow *pocket;
    int win_state;
    SKCropNode *cropNode;
    SKNode *crop;
    SKSpriteNode *crop1;
    SKSpriteNode *crop2;
    SKSpriteNode *crop3;
    PoolSkipButton *skip_button;
    NSDate *last_hit;
    NSDate *last_table_hit;
    SKAudioNode *drag_sound;
    shared_ptr_352a3a4b drag_sound2;
    NSString *mode;
    _Bool hit;
    _Bool first;
    int time;
    int first_hit;
}

@property int first_hit; // @synthesize first_hit;
@property _Bool first; // @synthesize first;
@property _Bool hit; // @synthesize hit;
@property int time; // @synthesize time;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)unload;
- (void)makeWalls:(struct b2World *)arg1;
- (struct b2FixtureDef *)makeFixture:(struct b2EdgeShape)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)shoot2;
- (void)shoot:(float)arg1 power:(float)arg2 spin_x:(float)arg3 spin_y:(float)arg4 save:(_Bool)arg5;
- (void)savePlaceBack:(id)arg1 what:(id)arg2;
- (void)placeBack:(id)arg1;
- (id)generatePreview;
- (id)getPreview;
- (void)sendMessage;
- (void)setBalls;
- (void)playReplay;
- (void)playNextReplay;
- (void)table_hit:(float)arg1;
- (void)ball_hit:(float)arg1;
- (void)addGlows;
- (id)parseReplay:(id)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)fixWhiteConflict;
- (void)fixBallConflict:(struct b2Body *)arg1;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (void)mMove;
- (float)rminus:(float)arg1 with:(float)arg2;
- (struct b2Body *)create:(int)arg1 x:(float)arg2 y:(float)arg3 density:(float)arg4 type:(int)arg5 wrld:(struct b2World *)arg6;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)resize;
- (void)skip;
- (void)resetBall:(struct b2Body *)arg1;
- (void)resetWhite:(_Bool)arg1;
- (void)resetWhite;
- (void)showWin;
- (void)update:(double)arg1;
- (void)receiveMessage:(id)arg1;
- (void)reset;
- (void)createSceneContents;
- (void)didMoveToView:(id)arg1;
- (id)initWithMain:(id)arg1 msg:(id)arg2;

@end

