//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString, SKLabelNode, SKNode;

@interface PoolCustomizePack : NSObject
{
    _Bool _unlocked;
    SKNode *_container;
    SKLabelNode *_label;
    NSMutableArray *_ids;
    NSMutableArray *_items;
    NSString *_store_id;
    struct CGPoint _original_position;
}

@property _Bool unlocked; // @synthesize unlocked=_unlocked;
@property struct CGPoint original_position; // @synthesize original_position=_original_position;
@property(retain) NSString *store_id; // @synthesize store_id=_store_id;
@property(retain) NSMutableArray *items; // @synthesize items=_items;
@property(retain) NSMutableArray *ids; // @synthesize ids=_ids;
@property(retain) SKLabelNode *label; // @synthesize label=_label;
@property(retain) SKNode *container; // @synthesize container=_container;
- (void).cxx_destruct;
- (void)setName:(id)arg1;
- (id)init;

@end

