//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ProtobufSizeCalculator : NSObject
{
}

+ (int)getMessageSize:(id)arg1 sizeCacheId:(int)arg2;
+ (int)getBytesSize:(id)arg1;
+ (int)getStringSize:(id)arg1;
+ (int)getBoolSize:(_Bool)arg1;
+ (int)getSFixed64Size:(long long)arg1;
+ (int)getSFixed32Size:(int)arg1;
+ (int)getFixed64Size:(unsigned long long)arg1;
+ (int)getFixed32Size:(unsigned int)arg1;
+ (int)getSInt64Size:(long long)arg1;
+ (int)getSInt32Size:(int)arg1;
+ (int)getUInt64Size:(unsigned long long)arg1;
+ (int)getUInt32Size:(unsigned int)arg1;
+ (int)getInt64Size:(long long)arg1;
+ (int)getInt32Size:(int)arg1;
+ (int)getFloatSize:(float)arg1;
+ (int)getDoubleSize:(double)arg1;
+ (int)getTagSize:(int)arg1;
- (id)init;

@end

