//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CodedOutputStream;

@interface ProtobufWriter : NSObject
{
    CodedOutputStream *output;
}

- (void)writeMessage:(id)arg1 sizeCacheId:(int)arg2;
- (void)writeBytes:(id)arg1;
- (void)writeString:(id)arg1;
- (void)writeBool:(_Bool)arg1;
- (void)writeSFixed64:(long long)arg1;
- (void)writeSFixed32:(int)arg1;
- (void)writeFixed64:(long long)arg1;
- (void)writeFixed32:(int)arg1;
- (void)writeSInt64:(long long)arg1;
- (void)writeSInt32:(int)arg1;
- (void)writeUInt64:(unsigned long long)arg1;
- (void)writeUInt32:(unsigned int)arg1;
- (void)writeInt64:(long long)arg1;
- (void)writeInt32:(int)arg1;
- (void)writeFloat:(float)arg1;
- (void)writeDouble:(double)arg1;
- (void)writeTag:(int)arg1 wireType:(int)arg2;
- (void)flush;
- (void)dealloc;
- (id)initWithOutputStream:(id)arg1;
- (id)init;

@end

