//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSInputStream, NSOutputStream, NSString, PSWebSocketBuffer;

@interface PSWebSocketServerConnection : NSObject
{
    _Bool _inputStreamOpenCompleted;
    _Bool _outputStreamOpenCompleted;
    NSString *_identifier;
    long long _readyState;
    NSInputStream *_inputStream;
    NSOutputStream *_outputStream;
    PSWebSocketBuffer *_inputBuffer;
    PSWebSocketBuffer *_outputBuffer;
}

@property(retain, nonatomic) PSWebSocketBuffer *outputBuffer; // @synthesize outputBuffer=_outputBuffer;
@property(retain, nonatomic) PSWebSocketBuffer *inputBuffer; // @synthesize inputBuffer=_inputBuffer;
@property(nonatomic) _Bool outputStreamOpenCompleted; // @synthesize outputStreamOpenCompleted=_outputStreamOpenCompleted;
@property(nonatomic) _Bool inputStreamOpenCompleted; // @synthesize inputStreamOpenCompleted=_inputStreamOpenCompleted;
@property(retain, nonatomic) NSOutputStream *outputStream; // @synthesize outputStream=_outputStream;
@property(retain, nonatomic) NSInputStream *inputStream; // @synthesize inputStream=_inputStream;
@property(nonatomic) long long readyState; // @synthesize readyState=_readyState;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)init;

@end

