//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameScene.h"

#import "UITextViewDelegate.h"

@class ActionButton, NSMutableArray, NSString, QuestionsAnswer, QuestionsAsk, SKCropNode, SKLabelNode, SKMultilineLabel, SKNode, SKSpriteNode, TipNode, UITextView;

@interface QuestionsScene : GameScene <UITextViewDelegate>
{
    int state;
    int player;
    NSString *player_id1;
    NSString *player_id2;
    SKSpriteNode *cross;
    SKSpriteNode *line1;
    SKSpriteNode *line2;
    QuestionsAsk *ask;
    NSMutableArray *questions;
    SKMultilineLabel *tip;
    SKNode *your_word;
    SKLabelNode *word;
    SKNode *list;
    SKCropNode *crop;
    SKNode *selected;
    struct CGPoint last_touch;
    SKLabelNode *your;
    ActionButton *send;
    NSString *answer;
    QuestionsAnswer *answer_ui;
    NSString *send_answer;
    _Bool keyboardIsShowing;
    SKSpriteNode *black;
    TipNode *wait;
    UITextView *textView;
}

@property(retain) UITextView *textView; // @synthesize textView;
- (void).cxx_destruct;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)skip;
- (void)resize;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)blink;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (void)update:(double)arg1;
- (struct CGPoint)Slerp:(struct CGPoint)arg1 pos2:(struct CGPoint)arg2 ratio:(float)arg3;
- (void)sendMessage;
- (void)nextAnswer;
- (void)toNextAnswer;
- (void)receiveMessage:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)resign;
- (void)Send;
- (void)hideWait2;
- (void)showWait2;
- (void)sendComplete;
- (void)SendGuessed;
- (void)SendSome;
- (void)SendNo;
- (void)SendYes;
- (void)createSceneContents;
- (void)didMoveToView:(id)arg1;
- (id)initWithMain:(id)arg1 msg:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

