//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class ActionButton, NSString, QuestionsQuestion, SKLabelNode, SKMultilineLabel, SKSpriteNode, Sprite;

@interface QuestionsAnswer : SKNode
{
    SKSpriteNode *shadow;
    SKMultilineLabel *q;
    SKNode *container;
    SKSpriteNode *answer_bg;
    SKSpriteNode *answer_shadow;
    SKLabelNode *answer;
    SKLabelNode *num;
    NSString *question;
    int answr;
    int num_i;
    Sprite *bg;
    ActionButton *yes;
    ActionButton *no;
    ActionButton *some;
    ActionButton *guess;
    QuestionsQuestion *_q;
}

@property(retain) QuestionsQuestion *q; // @synthesize q=_q;
@property(retain) ActionButton *guess; // @synthesize guess;
@property(retain) ActionButton *some; // @synthesize some;
@property(retain) ActionButton *no; // @synthesize no;
@property(retain) ActionButton *yes; // @synthesize yes;
@property(retain) Sprite *bg; // @synthesize bg;
- (void).cxx_destruct;
- (void)SetQuestion:(id)arg1 num:(int)arg2;
- (id)init;

@end

