//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameSettings.h"

#import "UITextFieldDelegate.h"

@class NSString, SettingsOptionPartition, UILabel, UITextField;

@interface QuestionsSettings : GameSettings <UITextFieldDelegate>
{
    SettingsOptionPartition *part1;
    UILabel *tip;
    UILabel *tip2;
    NSString *mode;
    UITextField *myTextField;
}

@property(retain) UITextField *myTextField; // @synthesize myTextField;
@property(retain) NSString *mode; // @synthesize mode;
- (void).cxx_destruct;
- (void)update;
- (void)resize;
- (id)init;
- (void)Sel;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)blink;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

