//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class QuestionsQuestion, SKMultilineLabel, SKSpriteNode, Sprite;

@interface QuestionsAsk : SKNode
{
    SKSpriteNode *shadow;
    SKMultilineLabel *q;
    SKNode *container;
    Sprite *bg;
    QuestionsQuestion *_question;
}

@property(retain) QuestionsQuestion *question; // @synthesize question=_question;
@property(retain) Sprite *bg; // @synthesize bg;
- (void).cxx_destruct;
- (void)setNumber:(int)arg1;
- (id)init;

@end

