//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameScene.h"

@class ActionButton, NSDate, NSMutableArray, NSString, RenjuStone, SKLabelNode, SKNode, SKShapeNode, SKSpriteNode, Sprite, TipNode, YouNode;

@interface RenjuScene : GameScene
{
    NSString *player_id1;
    NSString *player_id2;
    RenjuStone *piece;
    RenjuStone *piece2;
    SKSpriteNode *board;
    ActionButton *actionButton;
    TipNode *tip;
    NSMutableArray *win_stones;
    NSMutableArray *win_highlights;
    SKSpriteNode *highlight;
    Sprite *highlight2;
    NSMutableArray *pieces;
    NSMutableArray *dangers;
    NSMutableArray *map;
    SKNode *selected;
    float gap;
    float tile;
    _Bool sent;
    YouNode *you;
    float top;
    float bottom;
    float bottom2;
    float pressure;
    int time;
    NSMutableArray *replay;
    int player;
    int received;
    int state;
    _Bool mine;
    float left;
    float right;
    SKSpriteNode *basket1;
    SKSpriteNode *basket2;
    int win_state;
    NSMutableArray *particles;
    NSDate *last_swoosh;
    SKShapeNode *_spinnyNode;
    SKLabelNode *_label;
}

- (void).cxx_destruct;
- (void)update:(double)arg1;
- (void)replayMove;
- (int)checkWin;
- (void)showDanger;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (void)swoosh;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)receiveMessage:(id)arg1;
- (void)savePlaceBack:(id)arg1 what:(id)arg2;
- (void)placeBack:(id)arg1;
- (id)generatePreview;
- (id)getPreview;
- (void)sendComplete;
- (void)sendMessage;
- (void)resize;
- (void)createSceneContents;
- (void)Dust:(struct CGPoint)arg1;
- (void)didMoveToView:(id)arg1;
- (id)newPiece;
- (id)initWithMain:(id)arg1 msg:(id)arg2;

@end

