//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKSpriteNode.h"

@interface RenjuStone : SKSpriteNode
{
    _Bool down;
    int x;
    int y;
    int num;
    float z;
    SKSpriteNode *shadow;
    SKSpriteNode *stone;
}

@property _Bool down; // @synthesize down;
@property(retain) SKSpriteNode *stone; // @synthesize stone;
@property float z; // @synthesize z;
@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
@property int num; // @synthesize num;
@property int y; // @synthesize y;
@property int x; // @synthesize x;
- (void).cxx_destruct;
- (id)toString;
- (void)black;
- (void)white;
- (id)initWithBlack;
- (id)initWithWhite;
- (id)init;

@end

