//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class ChessPiece, NSMutableArray, SKSpriteNode;

@interface ReversiTip : SKNode
{
    _Bool op;
    _Bool _force;
    SKSpriteNode *tip;
    ChessPiece *castle;
    SKSpriteNode *mc;
    NSMutableArray *pieces;
    struct CGPoint pos;
}

@property _Bool force; // @synthesize force=_force;
@property _Bool op; // @synthesize op;
@property(retain) NSMutableArray *pieces; // @synthesize pieces;
@property(retain) SKSpriteNode *mc; // @synthesize mc;
@property(retain) ChessPiece *castle; // @synthesize castle;
@property struct CGPoint pos; // @synthesize pos;
@property(retain) SKSpriteNode *tip; // @synthesize tip;
- (void).cxx_destruct;
- (void)blink;
- (void)unblink;
- (id)init;

@end

