//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtobufMessage.h"

@class NSMutableArray, NSString;

@interface RoomInfo : NSObject <ProtobufMessage>
{
    int cachedSize;
    int cachedSizeId;
    int onlineUsers;
    NSString *identifier;
    NSString *roomType;
    NSMutableArray *roomData;
}

+ (id)roomInfoWithId:(id)arg1 roomType:(id)arg2 onlineUsers:(int)arg3 roomData:(id)arg4;
@property(retain) NSMutableArray *roomData; // @synthesize roomData;
@property int onlineUsers; // @synthesize onlineUsers;
@property(retain) NSString *roomType; // @synthesize roomType;
@property(retain) NSString *identifier; // @synthesize identifier;
- (int)sizeWithCacheId:(int)arg1;
- (void)deserializeFromReader:(id)arg1;
- (void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2;
- (id)initWithId:(id)arg1 roomType:(id)arg2 onlineUsers:(int)arg3 roomData:(id)arg4;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

