//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKSpriteNode;

@interface SeaCustomizeItem : SKNode
{
    int num;
    SKSpriteNode *cue;
    SKSpriteNode *cue_shadow;
    SKSpriteNode *enabled;
    SKSpriteNode *lock;
    SKSpriteNode *area;
}

@property(retain) SKSpriteNode *area; // @synthesize area;
@property int num; // @synthesize num;
@property(retain) SKSpriteNode *lock; // @synthesize lock;
@property(retain) SKSpriteNode *enabled; // @synthesize enabled;
@property(retain) SKSpriteNode *cue_shadow; // @synthesize cue_shadow;
@property(retain) SKSpriteNode *cue; // @synthesize cue;
- (void).cxx_destruct;
- (void)setType:(int)arg1;
- (id)init;

@end

