//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKSpriteNode.h"

@interface SeaJet : SKSpriteNode
{
    _Bool bombed;
    _Bool rotate;
    float speed;
    float angle;
    struct CGPoint pos;
}

@property float angle; // @synthesize angle;
@property _Bool rotate; // @synthesize rotate;
@property float speed; // @synthesize speed;
@property _Bool bombed; // @synthesize bombed;
@property struct CGPoint pos; // @synthesize pos;
- (void)setType:(int)arg1;
- (id)init;

@end

