//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class NSMutableArray, SKSpriteNode;

@interface SeaShip : SKNode
{
    NSMutableArray *glows;
    _Bool dead;
    int rot;
    int num;
    int dir;
    SKSpriteNode *sprite;
    NSMutableArray *hit;
    SKSpriteNode *shadow;
    struct CGPoint pos;
}

@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
@property _Bool dead; // @synthesize dead;
@property(retain) NSMutableArray *hit; // @synthesize hit;
@property(retain) SKSpriteNode *sprite; // @synthesize sprite;
@property int dir; // @synthesize dir;
@property int num; // @synthesize num;
@property int rot; // @synthesize rot;
@property struct CGPoint pos; // @synthesize pos;
- (void).cxx_destruct;
- (void)setTwitchRotation;
- (void)setRotation:(int)arg1 instant:(_Bool)arg2;
- (void)setRotation:(int)arg1;
- (struct CGPoint)max:(struct CGPoint)arg1;
- (id)hit2:(id)arg1;
- (_Bool)hit:(id)arg1;
- (_Bool)hit:(id)arg1 pos:(struct CGPoint)arg2;
- (int)hitPointWhere:(struct CGPoint)arg1;
- (_Bool)Bombed:(struct CGPoint)arg1;
- (void)Hit:(int)arg1;
- (void)Die;
- (_Bool)hitPoint2:(struct CGPoint)arg1;
- (_Bool)hitPoint:(struct CGPoint)arg1;
- (struct CGPoint)min:(struct CGPoint)arg1;
- (void)setShip:(int)arg1;
- (id)init;

@end

