//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameScene.h"

@class ActionButton, NSMutableArray, NSMutableString, NSString, SKMultilineLabel, SKNode, SKSpriteNode, SeaJet, SeaTarget, ShuffleButton, TipNode;

@interface SeaScene : GameScene
{
    int style1;
    int style2;
    SKSpriteNode *bg_node;
    SKSpriteNode *grid;
    NSMutableArray *reds;
    NSMutableArray *ships;
    NSMutableArray *bullets;
    NSString *ships1;
    NSString *bullets1;
    NSString *ships2;
    NSString *bullets2;
    NSString *skip_ships;
    NSString *player_id1;
    NSString *player_id2;
    SKNode *map;
    SKNode *board;
    SKNode *selected;
    SeaTarget *target;
    struct CGPoint dragPos;
    struct CGPoint dragStart;
    struct CGPoint dragLast;
    SKSpriteNode *clouds;
    SKSpriteNode *clouds2;
    ActionButton *start;
    SKMultilineLabel *editor_label;
    TipNode *editor_tip;
    ShuffleButton *shuffle;
    int rotationTimer;
    float right;
    float left;
    float board_size;
    SeaJet *jet;
    NSMutableArray *particles;
    int time;
    int state;
    int player;
    NSMutableArray *replay;
    NSMutableString *replay_send;
    int win;
    NSString *mode;
    int map_size;
}

- (void).cxx_destruct;
- (void)resize;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (struct CGPoint)Slerp:(struct CGPoint)arg1 pos2:(struct CGPoint)arg2 ratio:(float)arg3;
- (void)update:(double)arg1;
- (void)endMove;
- (void)checkWin;
- (void)resetClouds;
- (void)shakeCamera:(id)arg1 duration:(float)arg2 amp:(float)arg3;
- (void)BombTo:(struct CGPoint)arg1;
- (id)ExportBullets;
- (void)saveShips;
- (id)ExportShips;
- (id)addShip:(int)arg1 rot:(int)arg2 atPos:(struct CGPoint)arg3;
- (void)setState:(int)arg1;
- (void)setState2;
- (void)setState102;
- (void)setState1;
- (void)Start;
- (void)playReplay;
- (void)endReplay;
- (void)playNextReplay;
- (void)receiveMessage:(id)arg1;
- (void)sendMessage;
- (void)Shuffle;
- (void)CleanBoard;
- (void)ShipsFromString:(id)arg1;
- (void)AddShips2;
- (void)AddShips0;
- (void)AddShips1;
- (void)AddShips;
- (void)LoadShips;
- (void)BulletsFromString:(id)arg1;
- (void)bomb:(struct CGPoint)arg1;
- (void)reset;
- (void)createSceneContents;
- (void)didMoveToView:(id)arg1;
- (id)initWithMain:(id)arg1 msg:(id)arg2;

@end

