//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKScene.h"

@class ActionButton, MSMessage, MessagesViewController, NSArray, SKNode, SKSpriteNode;

@interface SendScene : SKScene
{
    MSMessage *msg;
    NSArray *data;
    MessagesViewController *main;
    float ratio;
    struct CGSize stageSize;
    SKNode *screen;
    SKSpriteNode *bg;
    _Bool landscape;
    _Bool contentCreated;
    SKNode *send_node;
    SKSpriteNode *black;
    SKSpriteNode *send;
    ActionButton *auto_open;
    SKNode *selected;
}

- (void).cxx_destruct;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (id)playSound:(id)arg1;
- (void)buttonCancel;
- (void)buttonDown;
- (void)buttonUp;
- (void)resize;
- (void)updateButtons;
- (void)tapAuto;
- (void)createSceneContents;
- (void)didMoveToView:(id)arg1;
- (id)initWithMain:(id)arg1 msg:(id)arg2;

@end

