//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKView.h"

@class SKScene, SettingsScene, UIImageView;

@interface SettingsScreen : SKView
{
    UIImageView *close;
    SettingsScene *skScene;
    SKScene *sscene;
}

@property(nonatomic) __weak SKScene *sscene; // @synthesize sscene;
@property(retain) SettingsScene *skScene; // @synthesize skScene;
@property(retain) UIImageView *close; // @synthesize close;
- (void).cxx_destruct;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 scene:(id)arg2;
- (void)closeTapGesture:(id)arg1;
- (void)avatarsUnlocked;

@end

