//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AVAudioPlayer, NSMutableArray, SettingsLineView, SettingsTitleLabel, UIImageView;

@interface SettingsOptionPartition : UIView
{
    float ratio;
    struct CGPoint tap_origin;
    AVAudioPlayer *button_down;
    AVAudioPlayer *button_up;
    AVAudioPlayer *button_cancel;
    _Bool _dark;
    _Bool isButton;
    _Bool _isAutostyle;
    int _rows;
    NSMutableArray *lines;
    NSMutableArray *options;
    UIView *bg;
    UIView *container;
    SettingsLineView *line;
    SettingsTitleLabel *title;
    UIImageView *newicon;
    NSMutableArray *_row_lines;
    struct CGSize margin;
}

@property(retain) NSMutableArray *row_lines; // @synthesize row_lines=_row_lines;
@property int rows; // @synthesize rows=_rows;
@property _Bool isAutostyle; // @synthesize isAutostyle=_isAutostyle;
@property(retain) UIImageView *newicon; // @synthesize newicon;
@property _Bool isButton; // @synthesize isButton;
@property(retain) SettingsTitleLabel *title; // @synthesize title;
@property(retain) SettingsLineView *line; // @synthesize line;
@property(retain) UIView *container; // @synthesize container;
@property(retain) UIView *bg; // @synthesize bg;
@property struct CGSize margin; // @synthesize margin;
@property(retain) NSMutableArray *options; // @synthesize options;
@property(retain) NSMutableArray *lines; // @synthesize lines;
- (void).cxx_destruct;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)addNew;
- (void)setMargins:(struct CGSize)arg1;
- (void)update;
- (void)addButton:(id)arg1;
- (void)centerTitle;
- (void)centerFullTitle;
- (void)cutLine;
- (void)light;
- (void)dark;
- (void)SetRows:(int)arg1;
- (id)initWithText:(id)arg1 size:(struct CGSize)arg2;

@end

