//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AVAudioPlayer, SettingsLineView, UIImageView, UILabel;

@interface SettingsOptionButton : UIView
{
    AVAudioPlayer *button_down;
    AVAudioPlayer *button_up;
    AVAudioPlayer *button_cancel;
    struct CGPoint tap_origin;
    struct CGPoint lock_offset;
    _Bool _active;
    _Bool selected;
    float min_width;
    float selected_width;
    float _new_size;
    UILabel *label;
    SettingsLineView *line;
    UIImageView *icon;
    UIView *container;
    UIImageView *dot;
    UIImageView *lock;
    UIView *content;
}

@property float new_size; // @synthesize new_size=_new_size;
@property(retain) UIView *content; // @synthesize content;
@property(retain) UIImageView *lock; // @synthesize lock;
@property(retain) UIImageView *dot; // @synthesize dot;
@property float selected_width; // @synthesize selected_width;
@property float min_width; // @synthesize min_width;
@property _Bool selected; // @synthesize selected;
@property(retain) UIView *container; // @synthesize container;
@property(retain) UIImageView *icon; // @synthesize icon;
@property(retain) SettingsLineView *line; // @synthesize line;
@property(retain) UILabel *label; // @synthesize label;
- (void).cxx_destruct;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)updateSize:(float)arg1;
- (void)inactive;
- (void)active;
- (void)addIcon:(id)arg1;
- (void)addLock:(struct CGPoint)arg1;
- (void)addLock;
- (void)lay;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithText:(id)arg1 size:(struct CGSize)arg2;

@end

