//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKScene.h"

#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"

@class ActionButton, AvatarNode, MessagesViewController, NSString, SKCropNode, SKLabelNode, SKMultilineLabel, SKNode, SKSpriteNode, UITextField, UITextView;

@interface SettingsScene : SKScene <UITextViewDelegate, UITextFieldDelegate>
{
    int time;
    UITextView *textView;
    SKSpriteNode *black;
    SKNode *unlock_screen;
    ActionButton *unlock_button;
    ActionButton *restore_button;
    ActionButton *privacy_button;
    SKSpriteNode *unlock_sprite;
    SKSpriteNode *unlock_line;
    SKLabelNode *unlock_loading;
    SKLabelNode *unlock_text;
    AvatarNode *unlock_avatar1;
    AvatarNode *unlock_avatar2;
    AvatarNode *unlock_avatar3;
    SKNode *picker;
    SKCropNode *picker_mask;
    SKSpriteNode *picker_top;
    SKSpriteNode *picker_ring;
    SKSpriteNode *picker_ring2;
    SKLabelNode *restore_loading;
    SKNode *screen;
    SKNode *buttons;
    ActionButton *sound_button;
    ActionButton *music_button;
    ActionButton *send_button;
    _Bool landscape;
    _Bool contentCreated;
    struct CGSize stageSize;
    float ratio;
    SKMultilineLabel *send_tip;
    SKLabelNode *editor_soon;
    SKNode *selected;
    MessagesViewController *main;
    SKNode *editor;
    AvatarNode *avatar;
    SKSpriteNode *editor_arrow;
    SKSpriteNode *category1;
    SKSpriteNode *category2;
    SKSpriteNode *category3;
    SKSpriteNode *category4;
    SKSpriteNode *category5;
    SKSpriteNode *category6;
    struct CGPoint touchPos;
    SKCropNode *area1;
    SKCropNode *area2;
    SKNode *scroll1;
    SKNode *scroll2;
    SKSpriteNode *crop1;
    SKSpriteNode *crop2;
    int category;
    struct CGPoint last_touch;
    _Bool scrolled;
    UITextField *myTextField;
    NSString *from;
}

@property(retain) NSString *from; // @synthesize from;
- (void).cxx_destruct;
- (void)resize;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)setAvatarColor:(id)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)setPickerColor:(id)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (void)buyAvatars;
- (void)updateButtons;
- (void)setSend;
- (void)setSound;
- (void)setMusic;
- (void)hideUnlock;
- (void)showUnlock;
- (void)showUnlock2;
- (void)setCategory:(int)arg1;
- (void)setCategory6;
- (void)setCategory5;
- (void)setCategory4;
- (void)setCategory3;
- (void)setCategory2;
- (void)setCategory1;
- (void)update:(double)arg1;
- (void)updateUnlock;
- (float)brightness:(id)arg1;
- (void)restoreAvatars;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)goPrivacy;
- (void)keyboardWillShow:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)createSceneContents;
- (id)playSound:(id)arg1;
- (void)buttonCancel;
- (void)buttonDown;
- (void)buttonUp;
- (void)avatarsUnlocked;
- (void)didMoveToView:(id)arg1;
- (void)setMain:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

