//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface SettingsLineView : UIView
{
    float leng;
}

- (void)setLight;
- (void)setLightVertical;
- (void)setDarkVertical;
- (void)setDark;
- (void)setVertical;
- (void)setHorizontal;
- (void)setHorizontal2;
- (void)setDarkHorizontal;
- (void)setLightHorizontal;
- (void)setLength:(float)arg1;
- (void)lay;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithLength:(float)arg1;

@end

