//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class NSMutableArray, SKSpriteNode;

@interface ShuffleSegment : SKNode
{
    int score;
    SKSpriteNode *sprite;
    NSMutableArray *poly;
}

@property(retain) NSMutableArray *poly; // @synthesize poly;
@property int score; // @synthesize score;
@property(retain) SKSpriteNode *sprite; // @synthesize sprite;
- (void).cxx_destruct;
- (id)init;

@end

