//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKSpriteNode.h"

@interface ShuffleBumper : SKSpriteNode
{
    SKSpriteNode *sprite;
    SKSpriteNode *shadow;
}

@property(retain) SKSpriteNode *shadow; // @synthesize shadow;
@property(retain) SKSpriteNode *sprite; // @synthesize sprite;
- (void).cxx_destruct;
- (id)init;

@end

