//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ShuffleWall : NSObject
{
    int player;
    struct b2Body *body;
}

@property int player; // @synthesize player;
@property struct b2Body *body; // @synthesize body;
- (id)init;

@end

