//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtobufMessage.h"

@class NSString;

@interface SocialProfile : NSObject <ProtobufMessage>
{
    int cachedSize;
    int cachedSizeId;
    NSString *userId;
    NSString *displayName;
    NSString *avatarUrl;
    long long lastOnline;
    NSString *countryCode;
    NSString *userToken;
}

+ (id)socialProfileWithUserId:(id)arg1 displayName:(id)arg2 avatarUrl:(id)arg3 lastOnline:(long long)arg4 countryCode:(id)arg5 userToken:(id)arg6;
@property(retain) NSString *userToken; // @synthesize userToken;
@property(retain) NSString *countryCode; // @synthesize countryCode;
@property long long lastOnline; // @synthesize lastOnline;
@property(retain) NSString *avatarUrl; // @synthesize avatarUrl;
@property(retain) NSString *displayName; // @synthesize displayName;
@property(retain) NSString *userId; // @synthesize userId;
- (int)sizeWithCacheId:(int)arg1;
- (void)deserializeFromReader:(id)arg1;
- (void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2;
- (id)initWithUserId:(id)arg1 displayName:(id)arg2 avatarUrl:(id)arg3 lastOnline:(long long)arg4 countryCode:(id)arg5 userToken:(id)arg6;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

