//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKSpriteNode.h"

@class UIColor;

@interface Sprite : SKSpriteNode
{
    UIColor *tint;
    int test;
}

+ (id)spriteNodeWithImageNamed:(id)arg1;
@property int test; // @synthesize test;
- (void).cxx_destruct;
- (id)getTint;
- (void)setTint:(id)arg1;

@end

