//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKScene.h"

@class AvatarNode, SKButton, SKLabelNode, SKMultilineLabel, SKNode;

@interface StoreScene : SKScene
{
    _Bool created;
    int time;
    SKNode *scroll1;
    _Bool scrolled;
    SKButton *store1;
    SKButton *store2;
    SKButton *store3;
    SKButton *store4;
    SKButton *store5;
    SKButton *store6;
    SKButton *store7;
    SKButton *store8;
    SKNode *screen;
    SKNode *feedback;
    SKNode *write;
    SKButton *icon1;
    SKButton *icon2;
    SKButton *icon3;
    SKMultilineLabel *feed;
    SKLabelNode *feedback_label;
    SKLabelNode *write_label;
    _Bool landscape;
    struct CGSize stageSize;
    float ratio;
    SKNode *selected;
    AvatarNode *unlock_avatar1;
    AvatarNode *unlock_avatar2;
    AvatarNode *unlock_avatar3;
    AvatarNode *unlock_avatar4;
    AvatarNode *unlock_avatar5;
    struct CGPoint last_touch;
    struct CGPoint touchPos;
}

- (void).cxx_destruct;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchUpAtPoint:(struct CGPoint)arg1;
- (void)touchMovedToPoint:(struct CGPoint)arg1;
- (void)touchDownAtPoint:(struct CGPoint)arg1;
- (void)Facebook;
- (void)Twitter;
- (void)Email;
- (id)playSound:(id)arg1;
- (void)buttonCancel;
- (void)buttonDown;
- (void)buttonUp;
- (void)resize;
- (void)openStore8;
- (void)openStore7;
- (void)openStore6;
- (void)openStore5;
- (void)openStore4;
- (void)openStore3;
- (void)openStore2;
- (void)openStore1;
- (void)updateUnlock;
- (void)update:(double)arg1;
- (void)didMoveToView:(id)arg1;

@end

