//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKCropNode, SKLabelNode, SKSpriteNode;

@interface TanksWind : SKNode
{
    SKCropNode *cropNode;
    SKSpriteNode *crop;
    float power;
    SKSpriteNode *sprite;
    SKSpriteNode *sprite2;
    SKLabelNode *power_label;
}

@property(retain) SKLabelNode *power_label; // @synthesize power_label;
@property float power; // @synthesize power;
@property(retain) SKSpriteNode *sprite2; // @synthesize sprite2;
@property(retain) SKSpriteNode *sprite; // @synthesize sprite;
- (void).cxx_destruct;
- (void)setWind:(float)arg1;
- (id)init;

@end

