//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKSpriteNode.h"

@class TanksTank;

@interface TanksBullet : SKSpriteNode
{
    _Bool dead;
    TanksTank *tank;
}

@property(retain) TanksTank *tank; // @synthesize tank;
@property _Bool dead; // @synthesize dead;
- (void).cxx_destruct;
- (id)init;

@end

