//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKLabelNode, SKSpriteNode;

@interface TanksTank : SKNode
{
    int player;
    float power;
    SKSpriteNode *sprite;
    SKNode *barrel;
    struct b2Body *body;
    SKSpriteNode *arrow;
    SKSpriteNode *barrel_img;
    SKLabelNode *angle_label;
}

@property float power; // @synthesize power;
@property(retain) SKLabelNode *angle_label; // @synthesize angle_label;
@property(retain) SKSpriteNode *barrel_img; // @synthesize barrel_img;
@property(retain) SKSpriteNode *arrow; // @synthesize arrow;
@property struct b2Body *body; // @synthesize body;
@property(retain) SKNode *barrel; // @synthesize barrel;
@property int player; // @synthesize player;
@property(retain) SKSpriteNode *sprite; // @synthesize sprite;
- (void).cxx_destruct;
- (void)SetTank:(int)arg1;
- (void)Shoot;
- (id)init;

@end

