//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class NSString, SKLabelNode, SKSpriteNode;

@interface TipNode : SKNode
{
    SKLabelNode *tip;
    SKLabelNode *tip2;
    NSString *dots;
    float max_width;
    SKSpriteNode *border;
    NSString *string;
    struct CGSize offset;
}

@property(retain) NSString *string; // @synthesize string;
@property float max_width; // @synthesize max_width;
@property struct CGSize offset; // @synthesize offset;
@property(retain) SKSpriteNode *border; // @synthesize border;
- (void).cxx_destruct;
- (void)setTip:(id)arg1 save:(_Bool)arg2;
- (void)setTip:(id)arg1;
- (void)setArrow;
- (void)setTip:(id)arg1 color:(id)arg2 size:(float)arg3;
- (void)dot;
- (void)stopBlinking;
- (void)startBlinking;
- (void)setBorder:(_Bool)arg1 color:(id)arg2;
- (void)setColor:(id)arg1;
- (id)init;

@end

