//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class GameViewController, MSMessage, MessagesViewController, NSDate, NSMutableDictionary, NSString, NSTimer, UIActivityIndicatorView, UIImage, UIImageView, UILabel, UIView;

@interface TranscriptViewContoller : UIViewController
{
    NSTimer *timer;
    UIView *cell;
    UIView *error_overlay;
    UILabel *error_label;
    UIImageView *error_icon;
    UIActivityIndicatorView *error_indicator;
    UIView *bg;
    UIView *bg2;
    UIImage *preview_image;
    UIImageView *preview;
    UIImageView *play;
    UIView *border;
    UILabel *caption;
    UILabel *subcaption;
    GameViewController *game_vc;
    NSString *game_id;
    NSString *_id;
    NSString *num;
    MSMessage *msg;
    NSMutableDictionary *items;
    NSString *caption_text;
    NSString *dots;
    UIView *tint;
    _Bool show_dots;
    struct CGPoint touchStart;
    NSDate *last_touch;
    _Bool update_transcript;
    NSString *img_name;
    int time;
    _Bool stopped;
    _Bool appeared;
    MessagesViewController *main;
}

@property __weak MessagesViewController *main; // @synthesize main;
- (void).cxx_destruct;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)dealloc;
- (void)unload;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)ad;
- (void)DumpObjcMethods:(Class)arg1;
- (void)displayClassInfo:(Class)arg1;
- (void)tapGesture;
- (void)resize;
- (struct CGSize)getSize:(struct CGSize)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (_Bool)isDecember;
- (void)update;
- (void)stop;
- (void)unstop;
- (void)viewDidLoad;
- (id)initWithMain:(id)arg1;
- (id)customPreview;
- (void)dot;
- (id)defaultPreview;

@end

