//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameScene.h"

@class SKLabelNode, SKShapeNode;

@interface UpdateScene : GameScene
{
    SKShapeNode *_spinnyNode;
    SKLabelNode *_label;
}

- (void).cxx_destruct;
- (void)didChangeSize:(struct CGSize)arg1;
- (void)receiveMessage:(id)arg1;
- (void)resize;
- (void)createSceneContents;
- (void)didMoveToView:(id)arg1;
- (id)initWithMain:(id)arg1 msg:(id)arg2;

@end

