//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtobufMessage.h"

@class NSData, NSMutableArray, NSString;

@interface ValueObject : NSObject <ProtobufMessage>
{
    int cachedSize;
    int cachedSizeId;
    _Bool _bool;
    int valueType;
    int _int;
    unsigned int uInt;
    float _float;
    NSString *string;
    long long _long;
    double _double;
    NSData *byteArray;
    long long dateTime;
    NSMutableArray *arrayProperties;
    NSMutableArray *objectProperties;
}

+ (id)valueObjectWithValueType:(int)arg1 string:(id)arg2 int:(int)arg3 uInt:(unsigned int)arg4 long:(long long)arg5 _Bool:(_Bool)arg6 float:(float)arg7 double:(double)arg8 byteArray:(id)arg9 dateTime:(long long)arg10 arrayProperties:(id)arg11 objectProperties:(id)arg12;
@property(retain) NSMutableArray *objectProperties; // @synthesize objectProperties;
@property(retain) NSMutableArray *arrayProperties; // @synthesize arrayProperties;
@property long long dateTime; // @synthesize dateTime;
@property(retain) NSData *byteArray; // @synthesize byteArray;
@property double _double; // @synthesize _double;
@property float _float; // @synthesize _float;
@property _Bool _bool; // @synthesize _bool;
@property long long _long; // @synthesize _long;
@property unsigned int uInt; // @synthesize uInt;
@property int _int; // @synthesize _int;
@property(retain) NSString *string; // @synthesize string;
@property int valueType; // @synthesize valueType;
- (int)sizeWithCacheId:(int)arg1;
- (void)deserializeFromReader:(id)arg1;
- (void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2;
- (id)initWithValueType:(int)arg1 string:(id)arg2 int:(int)arg3 uInt:(unsigned int)arg4 long:(long long)arg5 _Bool:(_Bool)arg6 float:(float)arg7 double:(double)arg8 byteArray:(id)arg9 dateTime:(long long)arg10 arrayProperties:(id)arg11 objectProperties:(id)arg12;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

