//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtobufMessage.h"

@class NSMutableArray, NSString;

@interface WaitingGameRequest : NSObject <ProtobufMessage>
{
    int cachedSize;
    int cachedSizeId;
    NSString *identifier;
    NSString *type;
    NSString *senderUserId;
    long long created;
    NSMutableArray *data;
}

+ (id)waitingGameRequestWithId:(id)arg1 type:(id)arg2 senderUserId:(id)arg3 created:(long long)arg4 data:(id)arg5;
@property(retain) NSMutableArray *data; // @synthesize data;
@property long long created; // @synthesize created;
@property(retain) NSString *senderUserId; // @synthesize senderUserId;
@property(retain) NSString *type; // @synthesize type;
@property(retain) NSString *identifier; // @synthesize identifier;
- (int)sizeWithCacheId:(int)arg1;
- (void)deserializeFromReader:(id)arg1;
- (void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2;
- (id)initWithId:(id)arg1 type:(id)arg2 senderUserId:(id)arg3 created:(long long)arg4 data:(id)arg5;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

