//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class NSMutableArray, NSString, SKLabelNode, SKSpriteNode;

@interface WordbitsBlock : SKNode
{
    _Bool _active;
    int _type;
    int _px;
    int _py;
    NSMutableArray *_blocks;
    SKLabelNode *_txt1;
    SKLabelNode *_txt2;
    SKLabelNode *_txt3;
    SKLabelNode *_txt4;
    SKSpriteNode *_bg;
    NSString *_str;
}

@property(retain) NSString *str; // @synthesize str=_str;
@property(retain) SKSpriteNode *bg; // @synthesize bg=_bg;
@property(retain) SKLabelNode *txt4; // @synthesize txt4=_txt4;
@property(retain) SKLabelNode *txt3; // @synthesize txt3=_txt3;
@property(retain) SKLabelNode *txt2; // @synthesize txt2=_txt2;
@property(retain) SKLabelNode *txt1; // @synthesize txt1=_txt1;
@property _Bool active; // @synthesize active=_active;
@property int py; // @synthesize py=_py;
@property int px; // @synthesize px=_px;
@property(retain) NSMutableArray *blocks; // @synthesize blocks=_blocks;
@property int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)setType:(int)arg1 letters:(id)arg2;
- (id)init;

@end

