//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKNode.h"

@class SKLabelNode, SKSpriteNode;

@interface YouNode : SKNode
{
    SKSpriteNode *yaya;
    SKLabelNode *you;
    SKSpriteNode *you_bg;
}

@property(retain) SKSpriteNode *you_bg; // @synthesize you_bg;
@property(retain) SKLabelNode *you; // @synthesize you;
- (void).cxx_destruct;
- (void)setNickname:(id)arg1;
- (void)set_you;
- (id)init;

@end

